### ISSUE TITLE
Docker, pull access denied for synesthesiam/rhasspy-hassio-addon repository 

### ISSUE THREAD

**Issue by brBart** [synesthesiam/rhasspy-hassio-addon#1]
> Unable to find image 'synesthesiam/rhasspy-hassio-addon:latest' locally
docker: Error response from daemon: pull access denied for synesthesiam/rhasspy-hassio-addon, repository does not exist or may require 'docker login'.
See 'docker run --help'.

Is the docker image available?

**Comment by tonybart1337** [comment]
it's [synesthesiam/rhasspy-server](https://hub.docker.com/r/synesthesiam/rhasspy-server)
