### ISSUE TITLE
/usr/local/bin/python3: No module named rhasspy

### ISSUE THREAD

**Issue by dony71** [synesthesiam/rhasspy-hassio-addon#10]
I install rhasspy server via hass.io add-on and running OK
Now I try to install rhasspy command line
wget https://github.com/synesthesiam/rhasspy/blob/master/bin/rhasspy-cli
chmod +x rhasspy-cli
./rhasspy-cli --help
/usr/local/bin/python3: No module named rhasspy

What am I missing?

**Comment by synesthesiam** [comment]
Make sure to put `rhasspy-cli` in the `bin` directory. You'll also need to run the `create-venv.sh` script to pull down all of the necessary software for Rhasspy to run outside Docker.

**Comment by synesthesiam** [comment]
Sorry, the CLI is only intended for a local install of Rhasspy, where you've cloned to repo and run the `create-venv.sh` script. If you're looking for a way to control Rhasspy remotely, check out the [HTTP API](https://rhasspy.readthedocs.io/en/latest/usage/#http-api). This should work well with the Hass.IO add-on as well as a local server.
