### ISSUE TITLE
No feedback when downloading

### ISSUE THREAD

**Issue by rwchateau** [synesthesiam/rhasspy-hassio-addon#100]
When you press download you have no idea if rhasspy is downloading or not responding.  Maybe adding some progress bar?

**Comment by synesthesiam** [comment]
I would like to do this, but I'm not sure the best way. The browser itself isn't doing the downloading, it's the Rhasspy server. It's also happening in a separate thread from the web server, so it might be quite difficult to get any progress information pushed back through to the client.

**Comment by synesthesiam** [comment]
Added in 2.4.17
