### ISSUE TITLE
/api/text-to-speech : add site_id

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#102]
If having easy setup for base/satellite in the future, I think this endpoint should support passing a site_id so the base (master) rhasspy can forward this to a satellite if site_id isn't himself.

**Comment by KiboOst** [comment]
I don't know if satellites will get http api but if that's the case (that could be nice even with minimal settings as a lot should come from the master) we would better get a api/devices endpoint that return json of all devices site_id, ip, port, type master/stellite

 :smile:

**Comment by jbperrin88** [comment]
I'm looking for this too !

**Comment by synesthesiam** [comment]
This has been added in `master`. Will be pushed to Docker soon.

**Comment by KiboOst** [comment]
Nice !

Was asking myself about /api/listen-for-command also ?
I use it to get rhasspy ask for confirmation. It may be too early as this will concern master/satellite configuration, but we should send tts on siteId and listen for an answer on siteId also so we can handle all on a satellite.

**Comment by synesthesiam** [comment]
This should get folded into the `rhasspy-server-hermes` project.
