### ISSUE TITLE
Intent handling section is missing after the update

### ISSUE THREAD

**Issue by frkos** [synesthesiam/rhasspy-hassio-addon#104]
Hello everyone! I'm using the latest version of hass.io addon and I can't find intent handling section in settings anymore
I did fresh reinstall - no luck
I see the link but it doesn't work (http://localhost:12101/#profile-handle)

![Capture](https://user-images.githubusercontent.com/47523946/71272670-b777b980-2364-11ea-9366-aa60d6df1df5.JPG)

**Comment by synesthesiam** [comment]
You can need to do a full reload in your browser (CTRL + R). I renamed the "Home Assistant" section to the more generic "Intent Handling". Let me know if this doesn't work.

**Comment by frkos** [comment]
I tried from my PC and freon mobile phone... including clearing cache and full refresh. Unfortunately,  it's still missing... i have wake word section right after MQTT

Btw, here in  rhasspy/src/components/profile i still see file HomeAssistant.vue...

**Comment by Romkabouter** [comment]
Same issue here, I think since version 2.14.4.2

**Comment by synesthesiam** [comment]
Fixed in 2.14.4.4
