### ISSUE TITLE
Move Kaldi custom_words.txt outside of kaldi folder

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#116]
The `custom_words.txt` is deleted/emptied when I download the Kaldi profile files.

Is it possible to move it elsewhere so it can be safe when reinstalling or updating profile files?

**Comment by synesthesiam** [comment]
It is possible to move it elsewhere (the setting is `speech_to_text.kaldi.custom_words`), but I should do something better in this case. The `custom_words.txt` for Pocketsphinx and Kaldi need to be kept distinct, but there's no requirement that it be in the `kaldi` directory.

Maybe I should re-name it to `kaldi_custom_words.txt` or something...

**Comment by synesthesiam** [comment]
Fixed in 2.4.17
