### ISSUE TITLE
faster speed tts for Jabra 510 USB speaker

### ISSUE THREAD

**Issue by comperta** [synesthesiam/rhasspy-hassio-addon#119]
Hy,
In order to make Jabra 510 USB speaker to work with Rhasspy, we need to change the setting in /etc/asound.conf by adding some lines regarding to sampling rate. Otherwise, its tts always play 16000Hz wav file at faster speed which is too weird to be understood.

actually the /etc/asound.conf look like :

```
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
```

and for jabra we need : 

```
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
    rate 48000
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
```

Can we have a option in Hass.io: add-on details menu audio to force the rate at 48000 ?

**Comment by frkos** [comment]
I have the same problem... My mic volume is too low, so I need to amend asound.conf inside hassio addon.
Still trying to find a solution =(

**Comment by frkos** [comment]
I've found a way... please check my post here
https://community.rhasspy.org/t/hass-io-addon-make-rhasspy-use-custom-asound-conf/106

**Comment by comperta** [comment]
Thanks @frkos for the idea. But I can't do it with my system.
I use this image : https://github.com/home-assistant/hassos/releases/download/3.7/hassos_rpi3-3.7.img.gz  and I can't Run on host system this command  :
`sudo docker container ls | grep rhasspy`

I try this way : https://developers.home-assistant.io/docs/en/hassio_debugging.html
but I can't do anything ... everytime I try to copy, I have this error : 
`/.asoundrc: read-only file system`

**Comment by frkos** [comment]
Ohhh.... it is hassOS limitation(((
I have hassio installed over raspbian

Can you edit any files in this folder?
/usr/share/hassio/addons/git/75f2ff60/rhasspy

**Comment by keith721** [comment]
I have a Jabra 410 USB speaker and noticed this same thing, today.  Pre-recorded WAV files play fine, but anything recorded from the microphone (at 16KHz) is speeded up greatly, and sounds like chipmunk speech.  (This is probably why my wake word processing is failing.)

Found [this other asoundrc file](https://gist.github.com/ScottJWalter/3ec644d2eb180d145db2b42c6ad13b53) which works for properly recognizing and playing back speech at the correct pitch.  For both arecord and aplay output devices, I use the value 'sysdefault'.

**Comment by comperta** [comment]
Thanks @keith721 for the asoundrc file.
Did you use a hassOS like me ? 
I can't write the file inside my system.

**Comment by keith721** [comment]
I use a Debian Server system, with Docker containers.
To copy the asoundrc file into the container, I used the 'docker cp' command.

with hassOS, I'm not certain what is possible. :(

**Comment by comperta** [comment]
Hi @synesthesiam ,

any idea how I can do that on HassOS ?

**Comment by frkos** [comment]
@comperta could you check this?

> Can you edit any files in this folder?
> /usr/share/hassio/addons/git/75f2ff60/rhasspy

If you can edit, so just add COPY command to Dockerfile. I use this method

Or you can fork hassio addon on github

**Comment by comperta** [comment]
thanks @frkos but I can't find : 

> /usr/share/hassio/addons/git/75f2ff60/rhasspy

maybe I am doing something wrong :) 

the only way I find with hassOS to connect to docker is : 

> SSH access through port 22222 

but with this I am initially be logged in to Hass.io CLI.
 to acces to the host system I use the 'login' command. 


I will try fork hassio addon on github, but this is not "optimal"

**Comment by comperta** [comment]
I've found a way , thanks to you @frkos  (and @keith721 for the .asoundrc file)

this is what I have made :
https://developers.home-assistant.io/docs/en/hassio_debugging.html
=> use debugging mode on port 22222 with an authorized_keys on a USB drive

then access to the host system with : 
`login`
Run
`sudo docker container ls | grep rhasspy`
on host system (Rhasspy addon should be started) and find Rhasspy container ID
Run on host system to accessing the Rhasspy's container bash :
`docker exec -it 11c8a7e34ea6 /bin/bash`
here and below replace 11c8a7e34ea6 with **your** container id
Run , to use wget command :
`apt-get install wget`
Run to create .asoundrc
`wget https://gist.github.com/ScottJWalter/3ec644d2eb180d145db2b42c6ad13b53/raw/8c1f03e9f34ea6674f715297f9de08b4db9f4ebe/.asoundrc -P /root/`

With the command above we create .asoundrc which overrides default asound.conf
That’s all. You should see effect immediately

**Important note**: every time you restart Hassio addon you need to copy the file again

**Comment by comperta** [comment]
@synesthesiam  if you read this, and if you have time to implant this in the addon, this will be great :)

**Comment by synesthesiam** [comment]
OK, I think I see what you mean. A way to have Rhasspy copy a `.asoundrc` over to the home directory (`/root` in this case) when it starts?

**Comment by frkos** [comment]
@synesthesiam 
It would be really helpful for Hassio addon users🤓

**Comment by comperta** [comment]
@synesthesiam thanks for the reply, it will be great if you can also detect in the options panel (see my capture screen) the mention of a Jabra in the audio output and use the .asoundrc file for jabra

![image](https://user-images.githubusercontent.com/21957307/72014699-b39ecf00-3260-11ea-82bc-e747daeb34b2.png)

**Comment by synesthesiam** [comment]
Hass.io is supposed to set whatever you select as the default device in ALSA for the add-on. Does it not work to always describe settings for the default device in `asoundrc`?

**Comment by comperta** [comment]
Hi @synesthesiam ,

I think this should work

**Comment by comperta** [comment]
Hi @synesthesiam ,

thanks for the add option in CONFIG :
![image](https://user-images.githubusercontent.com/21957307/73137350-5d4ed000-4057-11ea-9147-f2f780d71cf1.png)

but should I put the "link" for the asoundrc file ? something like :
![image](https://user-images.githubusercontent.com/21957307/73137382-a868e300-4057-11ea-9bcf-ce9f53e5e35d.png)
or should I add the configuration directly here ?
![image](https://user-images.githubusercontent.com/21957307/73137414-d8b08180-4057-11ea-908a-b8d1c5fccbcf.png)

both of them not working .
the first option put " /share/rhasspy/profiles/fr/.asoundrc" inside the /root/.asoundrc and the seconde one I can't save the CONFIG.

did I make something wrong ?

**Comment by frkos** [comment]
Hi @comperta 
Yes, you can't copy and paste it
Please check my config here

https://community.rhasspy.org/t/hass-io-addon-make-rhasspy-use-custom-asound-conf/106/16?u=frkos

**Comment by comperta** [comment]
Hi @frkos 

"\n to have single line" 👍 

that works now.

**Comment by comperta** [comment]
Thank to everyone :-)
