### ISSUE TITLE
create-venv.sh and apt-get 

### ISSUE THREAD

**Issue by pasckosky** [synesthesiam/rhasspy-hassio-addon#127]
Hi, and happy 2020
I'm giving a look at the project.
Following the getting started guide, I proceeded with the instructions to install the system in virtualenv.

One issue: create-venv.sh script was about to uninstall a bunch of application out of my system (wine was one of them).

Reason is the --yes switch passed to the apt-get install command.
By running manual planning (passing through aptitude instead of cli) I was able to fix conflicts in my system and install everything needed, but luckyly I was able to intercept and stop the deletion only by looking at messages before the real .

May I suggest the use of --with-new-pkgs switch (or a similar switch that fits better)?
Disallowing automatic removal of components should be good. In case of real incompatibilites, it's better to stop process instead of deleting sw.

**Comment by synesthesiam** [comment]
Yikes! I didn't realize `--yes` would also *uninstall* software. I'm not sure about `--with-new-pkgs` yet, so I've just removed the `--yes` flags for now. At the very least, the user can review the changes before confirming.
