### ISSUE TITLE
Enhance Audio

### ISSUE THREAD

**Issue by simatao** [synesthesiam/rhasspy-hassio-addon#131]
Hi,
would be great if there was an output volume variable for the TTS sytem via ALSA or sounds in general. I have passive speakers and almost here nothing but when bumping up the volume to 200% it works quite fine.
also, because I struggled for a log time t see if my settings are right or wrong, it would be nice to have a quick soundcheck and mic check button to support debugging during installation.
Thanks, great tool!
T

**Comment by synesthesiam** [comment]
There is a button to test the microphones on the Settings page. Nothing for audio output, but I usually just use the "Speak" button on the main page to do a test text to speech.

Were you meaning something different?

**Comment by synesthesiam** [comment]
As of 2.4.17 there is a button in the web UI to play back the last recorded voice command for testing.
