### ISSUE TITLE
phonetisaurus download repository is missing

### ISSUE THREAD

**Issue by esdeboer** [synesthesiam/rhasspy-hassio-addon#134]
I'm trying to install rhasspy on my freeBSD system (after changing the shell scripts a bit to remove incompatible things)

build-from-source.sh wants to download Phonetisaurus from https://github.com/synesthesiam/phonetisaurus-2019/releases/download/v1.0/phonetisaurus-2019.tar.gz , but this repository does not exist, do you need to create it? 
I guess it is just the current master branch of AdolfVonKleist/Phonetisaurus and I can just clone it?

**Comment by synesthesiam** [comment]
Sorry, missed that in some repo cleanup. Correct link is now: https://github.com/synesthesiam/docker-phonetisaurus/raw/master/download/phonetisaurus-2019.tar.gz

If you get this working, would you be willing to share you script changes for FreeBSD?

**Comment by esdeboer** [comment]
Thanks that does download, trying to get it to compile now, it has some compile errors

I'll let you know if I get it to work, seems the included shflags doesn't detect getopts correctly, so it can't use the long command line options, I've hardcoded them into the script for now.

**Comment by synesthesiam** [comment]
If you can, please follow up with a pull request or discussion here: https://community.rhasspy.org/

Thanks!
