### ISSUE TITLE
Flask Import issue - Import troubleshooting for raspbian

### ISSUE THREAD

**Issue by templeofair** [synesthesiam/rhasspy-hassio-addon#14]
keep getting following error after executing **./run-venv.sh --profile en**

```
Traceback (most recent call last):
  File "app.py", line 23, in <module>
    from flask import (
ImportError: cannot import name 'Flask'
```

installation for Virtual Environment.

Installed package versions:
- Python 3.6.3
- Flask 1.0.3

Any solution?

**Comment by synesthesiam** [comment]
Did you run the `create-venv.sh` script?

**Comment by templeofair** [comment]
@synesthesiam yes. I thought I messed the the whole system so I started fresh. now I have problem with flair installation. any idea? :(

error message:

Could not find a version that satisfies the requirement torch>=1.0.0 (from flair>=0.4.1->-r requirements.txt (line 14)) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch>=1.0.0 (from flair>=0.4.1->-r requirements.txt (line 14))

**Comment by synesthesiam** [comment]
This seems to be a known issue with flair and Raspberry Pi's specifically. For now, delete the line with flair from requirements.txt and you should be good to go.

**Comment by templeofair** [comment]
@synesthesiam  that what I was thinking about it as a solution. but will I miss some functionality? what is the side effect? :)

**Comment by templeofair** [comment]
@synesthesiam another question. I'm using PYTHON VIRTUAL ENVIRONMENT. Do I need to activate it for rhassy installation? sorry if it's stupid question since I'm new in this topic :)

**Comment by templeofair** [comment]
and also new error:
```
creating build/temp.linux-armv7l-3.6
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/pi/Downloads/rhasspy/.venv/include -I/usr/local/include/python3.6m -c pywrapfst.cc -o build/temp.linux-armv7l-3.6/pywrapfst.o -std=c++11 -Wno-unneeded-internal-declaration -Wno-unused-function
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  pywrapfst.cc:464:32: fatal error: fst/script/getters.h: No such file or directory
   #include <fst/script/getters.h>
                                  ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for openfst
  Running setup.py clean for openfst
Successfully built jsgf2fst
Failed to build openfst
Installing collected packages: MarkupSafe, Jinja2, Werkzeug, itsdangerous, click, Flask, flask-swagger-ui, six, flask-cors, greenlet, pycparser, cffi, gevent, gevent-websocket, Flask-Sockets, pydash, urllib3, idna, chardet, certifi, requests, paho-mqtt, PyAudio, webrtcvad, python-levenshtein, fuzzywuzzy, pyee, adapt-parser, precise-runner, cerberus, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, pytz, protobuf, googleapis-common-protos, enum34, futures, grpcio, google-api-core, google-cloud-texttospeech, asn1crypto, cryptography, pyopenssl, openfst, pyparsing, jsgf2fst
  Running setup.py install for openfst ... error
    Complete output from command /home/pi/Downloads/rhasspy/.venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4me4td42/openfst/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rkxsavcn-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/Downloads/rhasspy/.venv/include/site/python3.6/openfst:
    running install
    running build
    running build_ext
    building 'pywrapfst' extension
    creating build
    creating build/temp.linux-armv7l-3.6
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/pi/Downloads/rhasspy/.venv/include -I/usr/local/include/python3.6m -c pywrapfst.cc -o build/temp.linux-armv7l-3.6/pywrapfst.o -std=c++11 -Wno-unneeded-internal-declaration -Wno-unused-function
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    pywrapfst.cc:464:32: fatal error: fst/script/getters.h: No such file or directory
     #include <fst/script/getters.h>
                                    ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/pi/Downloads/rhasspy/.venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4me4td42/openfst/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rkxsavcn-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/Downloads/rhasspy/.venv/include/site/python3.6/openfst" failed with error code 1 in /tmp/pip-build-4me4td42/openfst/
You are using pip version 9.0.1, however version 19.1.1 is available.
```

**Comment by synesthesiam** [comment]
No worries about all the questions; I'm here to help :)

The only functionality you'll lose by not including flair is being unable to use the [flair intent recognizer](https://rhasspy.readthedocs.io/en/latest/intent-recognition/#flair). This is a machine learning recognizer meant for cases where you have lots of sentences and expect to encounter unknown words/phrases (not typical).

You shouldn't need to activate the virtual environment if you're using the `run-venv.sh` or `bin/rhasspy` scripts. Both will activate the environment before doing anything else.

Your new error surprises me. Which version of Raspbian are you on?

**Comment by templeofair** [comment]
Thanks for your help :)

Raspbian ver:
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

I realized that in jsgf2fst we need openfst. it seems like this installation is failing. I'm trying to install it manually but it's like 20 min and still running. not sure if it's right solution.

**Comment by templeofair** [comment]
Ok I gave up with Virtual Environment. just wanted to try it. but any thanks I tried now with docker and now the server is up :) I have to try it out. Let's see if it works for me

**Comment by synesthesiam** [comment]
Thank you for trying. It sounds like I may need to go back to have OpenFST built from source on RPi's. It can take an hour, unfortunately.

**Comment by LarsKaptein** [comment]
I'm having the same issue with OpenFST in the create-venv.sh script. Can i comment something out to make it work?

**Comment by synesthesiam** [comment]
I don't think so, unfortunately. The whole problem is coming from Raspbian having a different version of OpenFST in their repos than regular Ubuntu. And, to top it off, having the version from apt-get installed will break my current build from source.

I'm going to have to build OpenFST from source and then adjust compiler flags for all of the other pieces that need it to point to that directory.

**Comment by LarsKaptein** [comment]
I forgot to mention, I am running Debian 9.9
I fixed the issue by building OpenFST from source (changed the create-venv.sh). There where also 2 spaces missing in curl lines, wich caused the script to crash. (space missing between "-sSfL" and "-o")

**create-venv.sh**
Line 91: curl -sSfL-o "${python_file}" "${python_url}"
Line 151: curl -sSfL-o "${snowboy_file}" "${snowboy_url}"

When I finally tought I fixed everything i got the following error:
[https://pastebin.com/xYPaMD1Q](url)

I believe I have had this same yarn issue when i tried installing rhasspy a week ago, but I didn't have the OpenFST and curl errors back then as I recall.

**Comment by synesthesiam** [comment]
Thanks for sticking with it. Your error link didn't take me anywhere, so I'm not sure exactly what went wrong. For the time being, I just zipped up [dist directory](https://github.com/synesthesiam/rhasspy/releases/download/v2.0/rhasspy-web-dist.tar.gz) for you. It should be in the main Rhasspy directory.

For the OpenFST issues, I found the [openfst-python](https://pypi.org/project/openfst-python/) module, which builds OpenFST as part of its install process. As expected, it takes forever, but at least it's guaranteed to have the correct version!

**Comment by synesthesiam** [comment]
I've spent some more time on this, and I have a working solution for the Raspberry Pi 3 at least. Please update your git repo and re-run the `create-venv.sh` script.

**Comment by Ulrar** [comment]
Hi,

I tried removing openfst from the requirements.txt file and it did complete the install, but running rhasspy afterwards seems to still depend on it :

```
rhasspy@ha:~/rhasspy $ ./run-venv.sh --profile en
Traceback (most recent call last):
  File "app.py", line 26, in <module>
    from rhasspy.actor import ActorSystem, ConfigureEvent, RhasspyActor
  File "/home/rhasspy/rhasspy/rhasspy/__init__.py", line 23, in <module>
    from rhasspy.actor import ActorSystem, Configured, ConfigureEvent, RhasspyActor
  File "/home/rhasspy/rhasspy/rhasspy/actor.py", line 9, in <module>
    from rhasspy.profiles import Profile
  File "/home/rhasspy/rhasspy/rhasspy/profiles.py", line 9, in <module>
    from rhasspy.utils import recursive_update
  File "/home/rhasspy/rhasspy/rhasspy/utils.py", line 17, in <module>
    import pywrapfst as fst
ModuleNotFoundError: No module named 'pywrapfst'
```

Is there another place I should disable openfst, somewhere in rhasspy's config ? (Keeping in mind I can't access the web interface of course).
I've tried replacing my dist directory with mine but same result, although I'm on a pi2 so that might not work anyway.

thanks
