### ISSUE TITLE
Substitutions not working on 2.4.16

### ISSUE THREAD

**Issue by CommonBlob** [synesthesiam/rhasspy-hassio-addon#147]
Ive been having issues with substitutions not working on 2.4.15 when I first installed, and since with .16 too.

I put them in, it trains fine, but the substitution is not done in the intent.  Here is the sentences.ini entry:

```
[ChangeLightState]
light_name = ((hall light):hall){name}
light_state = (on | off) {state}

turn <light_state> [the] <light_name>
turn [the] <light_name> <light_state>
```

when i say, turn the hall light on it has hall light in name.  No errors are shown in the log, here is the debug entry for this:

`[DEBUG:6296083] __main__: {"text": "turn the hall light on", "intent": {"name": "ChangeLightState", "confidence": 1.0}, "entities": [{"entity": "name", "value": "hall light", "raw_value": "hall light", "start": 9, "raw_start": 9, "end": 19, "raw_end": 19}, {"entity": "state", "value": "on", "raw_value": "on", "start": 20, "raw_start": 20, "end": 22, "raw_end": 22}], "raw_text": "turn the hall light on", "tokens": ["turn", "the", "hall", "light", "on"], "raw_tokens": ["turn", "the", "hall", "light", "on"], "speech_confidence": 1, "slots": {"name": "hall light", "state": "on"}, "wakeId": "", "siteId": "default", "time_sec": `

I have redownloaded profiles again since upgrading.  Otherwise everything seems to work, with the exception of the substitution.

Btw, loving it so far, just wish i could get this working! :D

**Comment by CommonBlob** [comment]
Looks like an issue with fuzzywuzzy.  Working fine with OpenFST.

**Comment by synesthesiam** [comment]
Thanks for pointing this out! This will actually be a problem with every other intent recognizer besides `fsticuffs` (OpenFST) because of substitutions and converters. I'm working on fixes now in a side branch.

**Comment by synesthesiam** [comment]
Fixed in `master`. Will be in the next Docker image.

**Comment by CommonBlob** [comment]
Thank you Michael!
