### ISSUE TITLE
Incorrect generation of dictionary.txt

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#149]
During training (which fails silently), I get very strange entries in the `dictionary.txt` file in the `profile/fr/kaldi/model/` folder.

```
adam a d A~
('adam', 2)(a d a m)
```
This looks like a format issue...

Also got in the logs:
```
ERROR (arpa2fst[5.5]:Input():kaldi-io.cc:756) Error opening input stream /profiles/fr/kaldi/model/data/lang/words.txt
```
The `words.txt` file is not there (re-downloaded the profile + kaldi). No changes.

**Comment by synesthesiam** [comment]
Got it! This must've been a mistake during refactoring. It'll happen when there's more than one pronunciation for a word. Fixed in `master`.
