### ISSUE TITLE
Newest Docker image doesn't start

### ISSUE THREAD

**Issue by koenvervloesem** [synesthesiam/rhasspy-hassio-addon#15]
I have been running your Docker image of Rhasspy without any problems, but the latest updated I pulled fails to start with the following error:

```
usage: Rhasspy [-h] --profile PROFILE [--host HOST] [--port PORT]
               [--system-profiles SYSTEM_PROFILES]
               [--user-profiles USER_PROFILES] [--set SET SET]
Rhasspy: error: the following arguments are required: --profile/-p
```

The image is synesthesiam/rhasspy-server:latest@sha256:705299059fb163d2eaaa3c8fcba99d5ab6e14cd2186d4b9bec3218100bed810a.

Environment variables:

- RHASSPY_PROFILES | /profiles
- PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- LANG | C.UTF-8
- RHASSPY_APP | /usr/share/rhasspy
- CONFIG_PATH | /data/options.json

The RHASSPY_PROFILES path exists and has the same contents as before.

**Comment by synesthesiam** [comment]
Thanks for pointing this out. I forgot to mention that a profile name is now required on the command line. Additionally, the `RHASSPY_PROFILES` variable is deprecated. Use `--user-profiles` to change where Rhasspy writes data.

Check the Docker example on the README for one way of doing it.
