### ISSUE TITLE
Browser microphone throws an exception

### ISSUE THREAD

**Issue by timaschew** [synesthesiam/rhasspy-hassio-addon#150]
When clicking **use browser microphone** this is thrown in the browser console:

```
TranscribeSpeech.vue:258 Uncaught TypeError: Cannot read property 'getUserMedia' of undefined
    at u.getMicrophonePermission (TranscribeSpeech.vue:258)
    at n (vue.runtime.esm.js:2023)
    at HTMLInputElement.t._withTask.t._withTask (vue.runtime.esm.js:1822)
```

Happens on latest docker version and latest git commit via virtual-env.

**Comment by synesthesiam** [comment]
Which browser? I'm testing with Firefox 71 currently.

**Comment by timaschew** [comment]
I'm using macos and Brave.  
But Firefox and Chrome isn't working as well, but this is because I'm serving via http (without ssl).
This could be checked upfront with something like this:

```js
if (window.location.protocol != 'https:') {
  alert("microphone is only allowed via https")
  return
}
```

**Comment by synesthesiam** [comment]
Oh, I remember reading about this. Gotta love that they basically ruined the use of the browser microphone. If I recall, it's supposed to still work on `localhost` at least.

**Comment by timaschew** [comment]
True, it's totally stupid to have these kind of restrictions for localhost.

**Comment by gvs55** [comment]
This was the root of my issue as well. I was trying to test commands in the browser via http (as SSL / https is currently not functional).

You can workaround it by trusting the url specifically.

On Brave you can go to brave://flags/ and locate "Insecure origins treated as secure" , add the urls you want to be trusted and enable the option. After re-launching you should be able to use your microphone over http for the specified urls.

**Comment by krisha** [comment]
This is also a problem on Firefox if not running on localhost.

Related flags are "media.devices.insecure.enabled" and "media.getusermedia.insecure.enabled"  in about:config

**Comment by synesthesiam** [comment]
So would everyone agree this is something that should just be addressed in the documentation?

**Comment by gvs55** [comment]
I would agree. The docs or an FAQ. It's just one of those things that is confusing for new users. Certainly confused me for a little bit. 

Probably should be noted too that this is only an issue if you're connecting via http, and not https.

**Comment by krisha** [comment]
Yes. I think showing an error message could be nice also.

**Comment by synesthesiam** [comment]
Browser microphone will be removed in 2.5. It's too much trouble to depend on the whims of browser vendors :(
