### ISSUE TITLE
slot_programs only executed after saving slots

### ISSUE THREAD

**Issue by drhirn** [synesthesiam/rhasspy-hassio-addon#161]
I am experimenting with slot_programs to get some information from my smart home software (e.g. device names). Generally, it's working fine.
It reads in the docs, that the programs are executed with every training. This doesn't seem to be true. I only get new values after saving the "slots" in the web frontend which then triggers a training. Is this intended or am I doing something wrong?

**Comment by synesthesiam** [comment]
This seems to be an interaction with the training caching system. An easy fix is to force them to run each time (as I had intended). Should that be an option? Would anyone ever want to cache the results?

**Comment by drhirn** [comment]
To be honest: I've no idea what is best.
My plan was to trigger a training via HTTP API after changing a device in my smart home software. I tried to trigger saving the slots but it seems this is only possible when adding/editing slot values.

**Comment by synesthesiam** [comment]
Slot programs always run now in 2.4.17

**Comment by timaschew** [comment]
> My plan was to trigger a training via HTTP API

Yes that is also what I would like to do.

> Slot programs always run now in 2.4.17

What does mean always exactly?
