### ISSUE TITLE
Link to homeassistant (intent component) is not working

### ISSUE THREAD

**Issue by Santobert** [synesthesiam/rhasspy-hassio-addon#162]
The link to homeassistant (intent component) is not working:
![grafik](https://user-images.githubusercontent.com/15657682/72563479-1241f980-38ae-11ea-8c14-ebd72c4c43b3.png)

https://www.home-assistant.io/integrations/intent_script/ works.

**Comment by synesthesiam** [comment]
The link is not live yet because the `intent` component hasn't been rolled into a public release. The endpoint is coded and working in their development branch; I'm not sure why it didn't make it into the latest release.

**Comment by Santobert** [comment]
Oh well. Thanks for the quick answer 👍
