### ISSUE TITLE
Mbrola tool

### ISSUE THREAD

**Issue by marcteyssier** [synesthesiam/rhasspy-hassio-addon#166]
Hi,

First of all, thank you for your work.
I was using SNIP, but since I learned that the service was going to close, I installed Rhasspy and it was very easy to use.

I see a tools named Mbrola, link to Espeaker to add intonation on the robotic voice and the result is very nice.
https://github.com/numediart/MBROLA

Is it possible to integrate it in Rhasspy ? Or to use it ?

Regards
Marc

**Comment by djusHa** [comment]
Hi,

thanks for the tip, it sounds really good, but what we need is the `-s` speed option for espeak ;-)

Good news, it can be done. Mbrola implementation in rhasspy is very easy.
Bad news, you must build your own docker image.

Maybe i can make a pull request @synesthesiam ?

**Comment by synesthesiam** [comment]
This looks like a great tool. Is this in any way related to SSML?

To get started, one easy way to integrate this into Rhasspy would be through the [Command TTS system](https://rhasspy.readthedocs.io/en/latest/text-to-speech/#command). That simply calls an external program with the text string on standard in and expects WAV data on standard out.

> but what we need is the -s speed option for espeak ;-)

I've added an "arguments" option to the espeak profile config in the (upcoming) Rhasspy 2.4.18 :)

**Comment by djusHa** [comment]
If mbrola binary is already exist in /usr/bin and mbrola voice file is in /usr/share/mbrola/de5 for Example, it can be used like so (i've added the speed option myself):

![grafik](https://user-images.githubusercontent.com/13298022/74081592-ff57ba80-4a50-11ea-930e-cfc5a519be03.png)

In Docker file i'm using this to compile mbrola.

```
# compile mbrola
ARG mbrolaURI=https://github.com/numediart/MBROLA.git
WORKDIR /tmp
RUN mkdir mbrola && \
    mkdir -p /usr/share/mbrola && \
    cd mbrola && \
    git clone $mbrolaURI . && \
    make && \
    cp Bin/mbrola /usr/bin && \
    cd .. && \
    rm -rf mbrola
```

**Comment by synesthesiam** [comment]
Work on Rhasspy's text to speech support has moved to https://github.com/rhasspy/rhasspy-tts-cli-hermes
