### ISSUE TITLE
hermes microphone

### ISSUE THREAD

**Issue by or78rXxZ** [synesthesiam/rhasspy-hassio-addon#167]
i enable the hermes microphone and the system appears to acknowledge the configuration. when i wake up the system the log shows -
[DEBUG:5910816] HermesAudioRecorder: Recording from microphone (hermes)
[DEBUG:5910815] HermesAudioRecorder: started -> recording
[DEBUG:5910805] APlayAudioPlayer: ['aplay', '-q', '/usr/share/rhasspy/etc/wav/beep_hi.wav']
but it never responds to a sent mqtt message.

when i restart the system my mqtt log shows that rhasspy subscribes to the correct topic -
Jan 23 07:43:05 pi2 mosquitto[30193]: Received SUBSCRIBE from 12bae0a3-dbda-458b-97ed-9ac3e5b69499
Jan 23 07:43:05 pi2 mosquitto[30193]: #011hermes/audioServer/default/audioFrame (QoS 0)
Jan 23 07:43:05 pi2 mosquitto[30193]: 12bae0a3-dbda-458b-97ed-9ac3e5b69499 0 hermes/audioServer/default/audioFrame
Jan 23 07:43:05 pi2 mosquitto[30193]: Sending SUBACK to 12bae0a3-dbda-458b-97ed-9ac3e5b69499

when i send a audioframe message it is sent to rhasspy but rhasspy never acknowledges -
Jan 23 07:43:31 pi2 mosquitto[30193]: Received PUBLISH from heyu (d0, q0, r0, m0, 'hermes/audioServer/default/audioFrame', ... (44044 bytes))
Jan 23 07:43:31 pi2 mosquitto[30193]: Sending PUBLISH to 12bae0a3-dbda-458b-97ed-9ac3e5b69499 (d0, q0, r0, m0, 'hermes/audioServer/default/audioFrame', ... (44044 bytes))

what is the trick to getting this to work

**Comment by synesthesiam** [comment]
If you change nothing else, Rhasspy will expect to have silence after a voice command. So if you're trying to send a pre-recorded WAV file through MQTT, you may need to add silence to end of it.

**Comment by ludiazv** [comment]
Just a question a question on this. Does rasshapy is able to wake from a hermes mic?
I tested sending commands using the wake button from the web interface but I was not able to wake using a wake word configured.

**Comment by Romkabouter** [comment]
Yes, set Audio Recording to:
Get microphone input remotely with MQTT

**Comment by synesthesiam** [comment]
Closing unless there is more discussion.
