### ISSUE TITLE
[Enhancement] Add API endpoint to disable/enable Hot word detection

### ISSUE THREAD

**Issue by coxtor** [synesthesiam/rhasspy-hassio-addon#171]
Hi I am using Rhasspy with home assistant and it is working great. However, I am getting many false positive wake word activations using Snowboy with the wake word Jarvis in German, especially when watching movies. Having an endpoint to disable / enable wake word detection would be helpful.

**Comment by xLAva** [comment]
I implemented a proposal for that feature and created a pull request a few days ago.
Wake Word: activation/deactivation over HTTP API and MQTT Hermes #143

**Comment by synesthesiam** [comment]
I'll take another look at this and get back to you. This is definitely something that needs to be accessible, I just want to be careful about how.

**Comment by synesthesiam** [comment]
Being added in 2.4.18: the `/api/listen-for-wake` endpoint will accept "on" and "off" as POST data to enable/disable wake word.

**Comment by synesthesiam** [comment]
Added in 2.4.18
