### ISSUE TITLE
arecord: main:788: audio open error: Device or resource busy

### ISSUE THREAD

**Issue by basnijholt** [synesthesiam/rhasspy-hassio-addon#172]
I am trying to get Rhasspy working on Hass.io, Raspberry Pi 4, and PS Eye.

After the discussion [on the forum](https://community.rhasspy.org/t/hass-io-addon-make-rhasspy-use-custom-asound-conf/106/16) we can now add a `asound.conf` in the UI.

I use [this](https://community.rhasspy.org/t/hass-io-addon-make-rhasspy-use-custom-asound-conf/106/16?u=basnijholt) config because that person has the exact same setup as I do.

My microphone volume is too low, so (I believe) I need to use `asound` such that I can configure the microphone's volume.

PyAudio only works when I practically scream, however, I cannot get the ALSA option to work.

I selected it like
![image](https://user-images.githubusercontent.com/6897215/73597742-9b546400-452f-11ea-9000-a1503b8a9d99.png)
But now when I try to record something by clicking on the "Hold to Record" button:
![image](https://user-images.githubusercontent.com/6897215/73597749-bb842300-452f-11ea-8c7e-62ec4307e960.png)

Nothing is ever detected.

So I tried recording something using the terminal. I did:
```
export DOCKER=`sudo docker container ls | grep rhasspy | awk '{print $1}'`
sudo docker exec $DOCKER arecord -d 5 -r 16000 /tmp/test.wav
sudo docker cp $DOCKER:/tmp/test.wav .
# sudo docker exec $DOCKER aplay /tmp/test.wav
```
and then I get 
```
arecord: main:788: audio open error: Device or resource busy
```

Another user had the same issue (https://github.com/synesthesiam/rhasspy/issues/29), however, that one was closed due to inactivity (I suppose).
In contrast to the problem of that person, I get the error with [both these commands](https://github.com/synesthesiam/rhasspy/issues/29#issuecomment-541328110).

I would like to debug this, but not sure where to start?

**Comment by voipep** [comment]
Stupid question: Do you have another service running in the background e.g. Snips?

**Comment by basnijholt** [comment]
@voipep, thanks for your response. No, I have no other add-on or integration that uses the microphone.

**Comment by voipep** [comment]
I assume you already tried but I had a similiar problem and it worked when I selected another input device than default in the settings (try and error). Sorry that I can't help that much

**Comment by synesthesiam** [comment]
If Rhasspy is listening for a wake word when you exec into the Docker container, you'll definitely get the "busy" message. To start debugging, I'd advise turning off the wake word functionality and restarting Rhasspy.

In the most recent release (2.4.17), I also added a button to the web UI that I see on your screen (the green play button). After doing the "Hold to Record", speak, and release, you should be able to hit the button and hear the recorded command. This might help with debugging too.

**Comment by basnijholt** [comment]
> If Rhasspy is listening for a wake word

@synesthesiam, that was indeed the problem!

The microphone is working correctly now. On to solving the next [problem](https://github.com/synesthesiam/rhasspy/issues/181) :)
