### ISSUE TITLE
How should a native Android/iOS app integrate with Rhasspy?

### ISSUE THREAD

**Issue by grigio** [synesthesiam/rhasspy-hassio-addon#173]
Is there an official API to stream or send the voice audio to Rhasspy?
Is https://github.com/synesthesiam/rhasspy/pull/143 the raccomanded way to do it?

**Comment by synesthesiam** [comment]
The easiest way is to POST WAV data to `/api/speech-to-text` or `/api/speech-to-intent`. Rhasspy will automatically convert it for you and return the transcription or recognized intent.

If you want to stream audio continuously, there are a few options: via [MQTT](https://rhasspy.readthedocs.io/en/latest/audio-input/#mqtthermes) and using [GStreamer](https://rhasspy.readthedocs.io/en/latest/audio-input/#gstreamer) are probably the easiest.
