### ISSUE TITLE
Customize Rasa pipeline

### ISSUE THREAD

**Issue by daniele-athome** [synesthesiam/rhasspy-hassio-addon#174]
Currently Rhasspy has a hard-coded pipeline configuration for Rasa:

```
language: "{language}"
pipeline: "pretrained_embeddings_spacy"
```

Many times users need to customize their pipeline. For now I just modified the source code to use my own pipeline, but it would be nice to have this configured from within Rhasspy, or maybe in an external yaml file in the profile folder.

Thanks for this great piece of software!

**Comment by synesthesiam** [comment]
Thanks! Would it make sense to have an external YAML header file that gets written before the training data?

**Comment by daniele-athome** [comment]
[According to the documentation](https://rasa.com/docs/rasa/nlu/training-data-format/#markdown-format) there is nothing to put as a header to the training data so I think we can save it.

**Comment by synesthesiam** [comment]
[rhasspy-rasa-nlu-hermes](https://github.com/rhasspy/rhasspy-rasa-nlu-hermes) supports a custom YAML config file.
