### ISSUE TITLE
Docker latest tag does not work on RPi 4

### ISSUE THREAD

**Issue by Tooa** [synesthesiam/rhasspy-hassio-addon#176]
# Problem statement

Running `docker pull synesthesiam/rhasspy-server:armhf` on my RPi 4 causes the following error:

```bash
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/b245a33c684fdcade3ac4fe5683636f9a252d5a4559c83f75e5551a8f722c086/merged: too many levels of symbolic links
```

* RPi 4 (4GB RAM version)
* OS: Raspbian GNU/Linux 10 (buster)
* Docker version 19.03.6, build 369ce74
* Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

# Expected Behaviour

```bash
$ docker pull synesthesiam/rhasspy-server:armhf
$ echo $?
0
```

# Actual Behaviour

```bash
$ docker pull synesthesiam/rhasspy-server:armhf
armhf: Pulling from synesthesiam/rhasspy-server
60341935f70d: Already exists
[...]
b1656fdeceae: Extracting [==================================================>]  125.2kB/125.2kB
75068175732c: Download complete 
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/f982c0bb3340322879621e9ceb246baabd65e290fb2dd0118381c51d9976e1d9/merged: too many levels of symbolic links
$ echo $?
1
```

# Details

* `docker pull synesthesiam/rhasspy-server:armhf-2.3` works
* I guess we reached the limit of docker layers for Raspbian here
  * In contrast, HASS.io is modified to run more docker layers ([reference](https://github.com/home-assistant/supervisor/issues/1383))

**Comment by synesthesiam** [comment]
This is surprising, since I thought the 2.4 image used far fewer layers than 2.3. Did they lower the limit?

**Comment by Tooa** [comment]
Seems like this issue is resolved with the latest docker update (Docker version 19.03.7, build 7141c19). I'm now able to pull the latest docker image of rhasspy. Thus, closing this issue.
