### ISSUE TITLE
Send intents to Home Assistant link broken

### ISSUE THREAD

**Issue by Tooa** [synesthesiam/rhasspy-hassio-addon#177]
# Problem statement

The link in the web interface `Settings -> Intent Handling` [here](https://github.com/synesthesiam/rhasspy/blob/3eb4368b37ca86dad4ab7aa0c7cd4b7e96d32722/src/components/profile/IntentHandling.vue#L89) is broken i.e. returns `Page Not Found`.

# Details

* Rhasspy version: 2.4.18

**Comment by Romkabouter** [comment]
Please confirm if this is fixed in 2.4.19.

I cannot reproduce this issue

**Comment by Tooa** [comment]
Version `2.4.19` still references a broken link:

https://github.com/synesthesiam/rhasspy/blob/v2.4.19/src/components/profile/IntentHandling.vue#L89

**Comment by synesthesiam** [comment]
Will be fixed in 2.4.20
