### ISSUE TITLE
Porcupine wake word not working

### ISSUE THREAD

**Issue by Coelhomatias** [synesthesiam/rhasspy-hassio-addon#178]
Hi,
I’m having trouble using the porcupine wake word, installed rhasspy with docker and only changed the microphone and sound output. I’m getting this error on start:

ERROR:PorcupineWakeListener:loading wake handle
Traceback (most recent call last):
File “/usr/share/rhasspy/rhasspy/wake.py”, line 852, in in_started
self.load_handle()
File “/usr/share/rhasspy/rhasspy/wake.py”, line 936, in load_handle
sensitivities=self.sensitivities,
File “/usr/share/rhasspy/porcupine.py”, line 98, in init
init_func = library.pv_porcupine_multiple_keywords_init
File “/usr/lib/python3.6/ctypes/init.py”, line 361, in getattr
func = self.getitem(name)
File “/usr/lib/python3.6/ctypes/init.py”, line 366, in getitem
func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /profiles/en/porcupine/libpv_porcupine.so: undefined symbol: pv_porcupine_multiple_keywords_init

my profile.json is like this:

`{
    "microphone": {
        "pyaudio": {
            "device": "2"
        }
    },
    "wake": {
        "system": "porcupine"
    },
    "sounds": {
        "system": "aplay",
        "aplay": {
             "device": "sysdefault:CARD=seeed2micvoicec"
        }
    },
    "rhasspy": {
        "listen_on_start": true
    }
}`

Can you help pls?
Thank you

**Comment by Tooa** [comment]
Hi,
I have the same problem and everyone re-downloading the models will end up with this error ([reference](https://community.rhasspy.org/t/porcupine-wake-word-not-working/511)). 

The Porcupine team changed its Python wrapper (https://github.com/Picovoice/porcupine/commit/f5660d43d7b565196151cffb172cfcb715887b9f). As `Rhasspy` always fetches the latest Porcupine binaries, the Python binding versioned in `Rhasspy` does not match anymore.

* Quick fix: Replace porcupine.py Python binding (https://github.com/synesthesiam/rhasspy/pull/180)
* In the long term `Rhasspy` should stick to release tags if available for model downloads

**Comment by basnijholt** [comment]
@Tooa, great! Thanks for finding out what's happening 😄

**Comment by synesthesiam** [comment]
Pull request has been merged :)

**Comment by basnijholt** [comment]
@synesthesiam, will you release a new version soon that includes that fix?

**Comment by Tooa** [comment]
@Coelhomatias Can you close this issue since the fix is published with `2.4.19` ([reference](https://github.com/synesthesiam/rhasspy/commit/331138f300b1dc3d8cb8f31020b29bc19224fe81#diff-d3bb3391c79904494c60ee2ac2f33070R10))
