### ISSUE TITLE
[solvded] no sound, no 'audio output' in profile.json 

### ISSUE THREAD

**Issue by pploume** [synesthesiam/rhasspy-hassio-addon#185]
Hi,

I'm running (as pi user) rhasspy 2.4.18 on a PI 3B +seed2micvoicec with Home Assistant ... 
Every thing seems to work correctly, microphone is OK, but not TTS from Rhasspy.

In setting/Audio Playing:
- I don't have "use PyAudio (default)" like for setting/Audio Recording
- I've checked "Use aplay directly (ALSA)
and for 'Output Device'  I can see 'default:CARD=seed2micvoicec: Default Audio Output' 
but when I select this option + 'save setting' ... it seems to be stuck to 'Default Device'
and not saving the option selected.

here is my profile.json
{
    "handle": {
        "system": "hass"
    },
    "home_assistant": {
        "access_token": "myToken",
        "url": "http://192.168.0.2:8123"
    },
    "microphone": {
        "pyaudio": {
            "device": "2"
        }
    }
}
 I've not been able to find info/doc on "Microphone:" entry 
I understand there is no configuration for audio output for rhasspy (or tts service)
(bth, from shell aplay test.wav works perfectly ...)

Any suggestion and help will be appreciated
(I tryed docker container: no audio output https://github.com/synesthesiam/rhasspy/issues/113, not working for me)

**Comment by frkos** [comment]
Hi @pploume 
Do you run Rhasspy as hassio addon? Or docker container?

Also maybe you can try to add Output device manually in your profile? Don't forget to ctrl+F5 in your browser, as it may store old config in cache
https://rhasspy.readthedocs.io/en/latest/audio-output/

**Comment by pploume** [comment]
Hi @frkos  
Thanks for your interest

Probleme solved by creating asound.conf for Docker environnement ...
