### ISSUE TITLE
Docker pull stucks 

### ISSUE THREAD

**Issue by ajinkyaw** [synesthesiam/rhasspy-hassio-addon#188]
Hey guys,
I am newbie to docker and these things.
I am trying to pull the synesthesiam/rhasspy-server in docker on Raspberry PI Stretch, 
but the downloading / extracting operation stucks in between.

below is the stage where it happens,,

latest: Pulling from synesthesiam/rhasspy-server
60341935f70d: Already exists 
3df2b7c380f8: Already exists 
8c9d3d2adfb5: Already exists 
dac0b57271f8: Already exists 
b265cc8ce38c: Already exists 
243180c9ceb6: Already exists 
c2884d922b16: Already exists 
094fece1b4e8: Already exists 
2231cbfd79c1: Already exists 
c596286de0bb: Already exists 
3683df8fa0e0: Already exists 
5b617c77a58a: Already exists 
7c4a50408b26: Already exists 
0e942a95b8d9: Pull complete 
8d6ac053beca: Pull complete 
02aae7f1e7ef: Pull complete 
0fa7794de7f9: Pull complete 
10431383ce03: Extracting [=========================================>         ]  10.09MB/12.3MB
f14536d0f02c: Download complete 
868659040a9e: Download complete 
43551b46647c: Download complete 
9daac113506c: Download complete 
8479e3aa2322: Download complete 
43519cfcc120: Waiting 
c4d297dc6f0e: Waiting 
07f95d87fde9: Waiting 
78524a0585c3: Waiting 
a9a8dd3ce47a: Waiting 
c3978ed95343: Pulling fs layer 
46d188ef3188: Waiting 
199b3c46f132: Pulling fs layer 
bc5d2cb6374a: Waiting 
d2de69fa2257: Waiting 
769d7ebc737e: Waiting 
5bd9cf270cec: Waiting 
690f382bb10a: Waiting 
48609f288de4: Waiting 

After searching a lot on internet , i tried an option to change max downloads to 1.
but then no luck again.

I apologise if this question is not relevant or related to this topic, but i found no accurate forum to post this. Maybe posting here could lead me somewhere hence posting.

Please do guide me to resolve this issue if known.

**Comment by synesthesiam** [comment]
Did this get resolved with the latest version of Docker?
