### ISSUE TITLE
Financial support ?

### ISSUE THREAD

**Issue by poofyteddy** [synesthesiam/rhasspy-hassio-addon#192]
Hello
I still haven't start using Rhasspy, But this project is very important to me.
I was planing to do a hole house Assistant with Snips, but this is nolonger an option.
As a French speaker, and absolutely not a dev, very little (to not say none) of the solution i've found are both multi-lingual and Fully local.

I'm seeing great talk about tone's of stuff that i would like to have, and i really want this project to keep improving.
Sadly since i can't provide code, I'm wondering if there is something to support financially this project. I'm personally talking small, like 2-5$ a month, but still something.
I'm also wondering if this is something OK with other people helping on this, since support goes only to the repo owner.

**Comment by maxbachmann** [comment]
There was a similar question on the forum a couple of days ago. Here is the answer of @synesthesiam 
https://community.rhasspy.org/t/documentation-preview-for-2-5/516/4

**Comment by synesthesiam** [comment]
Hoping to find a way to have community donations go directly to the Digital Ocean Discourse droplet...
