### ISSUE TITLE
Sound Device not saving in profile.json

### ISSUE THREAD

**Issue by DeadEnded** [synesthesiam/rhasspy-hassio-addon#194]
After updating my docker image, and completely rebuilding my EN profile (done while troubleshooting porcupine issue) I found that my sound device was not working.  After some digging I found that profile.json was not being saved with new sound device unless I selected "no playback on this device".  Then it would put in the dummy value.  If I selected aplay and then selected any device from the list - nothing was entered into profile.json.

I manually entered my sound device using my previous profile.json value (yay backups) and it was fixed.  So there appears to be a bug that is not saving profile.json when sound device is changed.

As always thank you for this awesome software!

**Comment by cyaelcastro** [comment]
Can you share your profile.json file

**Comment by DeadEnded** [comment]
Here is my profile.json after I fixed it.
```
{
    "microphone": {
        "arecord": {
            "device": "sysdefault:CARD=USB"
        },
        "system": "arecord"
    },
    "sounds": {
        "aplay": {
            "device": "sysdefault:CARD=USB"
        }
    },
    "speech_to_text": {
        "system": "kaldi"
    },
    "text_to_speech": {
        "system": "picotts"
    },
    "wake": {
        "porcupine": {
            "keyword_path": "porcupine/jarvis.ppn"
        },
        "system": "porcupine"
    }
}
```

The part I had to add manually is this:
```
    "sounds": {
        "aplay": {
            "device": "sysdefault:CARD=USB"
        }
   }
```

**Comment by Xalip** [comment]
So your issue is fixed? Isn't it?

**Comment by DeadEnded** [comment]
Manually editing the profile.json fixes it.  The system works, but the GUI does not save changes to the file from my experimentation.

**Comment by Xalip** [comment]
Hopefully v2.5 will fix this issue.

**Comment by FuzzyMistborn** [comment]
I've noticed something similar with my Pi3 (doesn't happen on the 4 i also have).  Can't save anything in the GUI, says it saves, restarts and then....no change.  Tried importing a working profile and it doesn't load either.

**Comment by amadib** [comment]
I had to do the same!

**Comment by synesthesiam** [comment]
Are the permissions messed up in your profile directory? This can happen if you run/save with Docker and then go back to a venv.

**Comment by DeadEnded** [comment]
I don't think the permissions have changed....
I have been using Docker since day 1, no environment changes.
It just started doing this after I updated back in early March.
Today I updated to 2.4.20 and this appears to be fixed.

I will close this issue as it appears to have been resolved with the newest version.
Thanks!
