### ISSUE TITLE
Can't pull on a pi 3b+ with docker

### ISSUE THREAD

**Issue by FuzzyMistborn** [synesthesiam/rhasspy-hassio-addon#195]
I've tried pulling the docker image several times and keep getting the error (while it's extracting) `failed to register layer: Error processing tar file(exit status 1): unexpected EOF`

It installed fine on my main server.

**Comment by Xalip** [comment]
What command are you executing? Please paste your command in here.

**Comment by FuzzyMistborn** [comment]
Straight from the instructions:

`docker run -p 12101:12101       --restart unless-stopped       --name rhasspy       -v "/home/pi/rhasspy/profiles:/profiles"       --device /dev/snd:/dev/snd       synesthesiam/rhasspy-server:latest       --user-profiles /profiles       --profile en
`

I've even tried just a straight `docker pull synesthesiam/rhasspy-server:latest` and still no luck.

**Comment by FuzzyMistborn** [comment]
Sigh. I'm dumb. Pulling an amd_64 image for an arm device. Pulled right version and it works.

**Comment by FuzzyMistborn** [comment]
Take that back. Didn't complete.  Errors out here. 

c20202f77b42: Extracting  35.39MB/35.39MB
8d6ac053beca: Download complete
33065a64e5ff: Download complete

**Comment by FuzzyMistborn** [comment]
Ok trying again for like the 10th time it pulled on latest.  Weird.  Anyway closing.
