### ISSUE TITLE
/api/listen-for-wake does not work as described

### ISSUE THREAD

**Issue by derrohrbach** [synesthesiam/rhasspy-hassio-addon#200]
The listen-for-wake api does not work as described in https://rhasspy.readthedocs.io/en/latest/reference/#endpoints. It can not disable the wake word detection and only enables it once, if you set the listen to wake word on startup option to false. 

Also a GET request for the current status of wake word detection would be nice, because you could then connect it to a REST Switch in HASS

**Comment by synesthesiam** [comment]
POST will work correctly in v2.5 (which doesn't have the listen on startup option). Let me look into the GET.

**Comment by derrohrbach** [comment]
Updated to 2.4.20 today, now POST works!
