### ISSUE TITLE
ModuleNotFoundError: No module named 'attr'

### ISSUE THREAD

**Issue by krawa** [synesthesiam/rhasspy-hassio-addon#205]
After update to 2.4.20 Rhasspy Assistant does not start.
Error log.

```
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```
Home Assistant 0.108.5
HassOS 3.13
Raspberry pi 3b+
arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.114-v7
python_version | 3.7.7
version | 0.108.5

**Comment by pheelee** [comment]
fixed this in my pull request: https://github.com/synesthesiam/rhasspy/pull/207
and https://github.com/synesthesiam/hassio-addons/pull/11

**Comment by synesthesiam** [comment]
Doing a rebuild now. The Google libs add around 5 hours to the Pi builds, unfortunately.

**Comment by krawa** [comment]
The problem is gone. Thanks!
