### ISSUE TITLE
Settings and Advanced tabs to not reflect each others changes

### ISSUE THREAD

**Issue by DeadEnded** [synesthesiam/rhasspy-hassio-addon#206]
I'll be honest - I noticed this when the Advanced tab was first added - but never reported it because I wasn't using the Advanced tab so it didn't bother me.  At this point though so much has gone into this I am wondering if it is only my setup as I have not seen anyone else report it.

Anyway, I have found that if I make a change in Settings tab and save it - the Advanced tab still has the old values.  Even if I restart Rhasspy they do not always since.

After updating to 2.4.20 I did a test...
Initial value of wake word sensitivity 0.2.
Change Settings to 0.3 - change is reflected in profile.json, but not Advanced tab.
Change Advanced tab to 0.4 - change is reflected in profile.json, but not Settings tab.
Change Settings tab back to 0.2 - change is reflected in profile.json but not Advanced tab.
Restarted Rhasspy container... and this is where it gets even weirder....  profile.json is still 0.2, Settings is 0.3, and Advanced is 0.4! 

So anyway, this is a very minor but - and might not effect other users - could just be me... but it seems that the Settings and Advanced tabs do not sycn with each other, and that they may cache their data instead of always pulling fro profile.json.

I hope that is all clear!
Thanks again!
DeadEnd

**Comment by litinoveweedle** [comment]
I can second this issue, but it was present even in 2.4.19. I did found it in both Rhasspy Docker and Hassio addon. It seem, that for some reason it could happened, that Rhasspy stop writing profile.json corectly into Docker shared volume. So if you do change via Rhasspy web it is present and will survive Rharrpy restart. But if you restart host machine all configuration changes are lost (as changes are not written into host machine shared directory with profiles). Side effect of this issue is, that whatever is in advance tab doesn't at all reflect content of profile.json file.

**Comment by synesthesiam** [comment]
I haven't been able to test in Hass.io myself for a while now. It's such a moving target that I have trouble keeping up. Is there some new magic setting for having changes to `/share` persist across reboots?

**Comment by DeadEnded** [comment]
I am using Docker container - not the add-on.
I have a volume mapped so that all configuration files are preserved.
This issue has been present since I believe the Advanced tab was introduced (many months ago).
It is not a new issue, but something I have not noticed reported and so I thought I would share.

Again, is summary - both the Settings and Advanced tab appear to update profile.json when saved - but if you change one, the other does not reflect the change.  So if you make a change in the Settings tab and save, you will still see the OLD value in the Advanced tab, and vice versa.

Cheers!

**Comment by litinoveweedle** [comment]
Hello,
so it seem my problem is different - as in my case, not only advance tab shows completely strange differences, but also changes are not being written into profile.json anymore. I don't think so, that my problem is Hassio issue, maybe some strange Docker bug? Anyway sorry for confusion. For anyone having my kind of issue, solution is to drop and recreate Docker container. You can keep shared data (i.e. profile data) in the Docker volume.

**Comment by DeadEnded** [comment]
Closing issue as Rhasspy code has been completely overhauled with 2.5 release.
