### ISSUE TITLE
Rhasspy Docker 2.4.20 could not download required Porcupine files

### ISSUE THREAD

**Issue by litinoveweedle** [synesthesiam/rhasspy-hassio-addon#208]
Hello,
If existing porcupine directory (from previous installations) in profiles directory on host machine is removed, Rhasspy 2.4.20 could not download its content. 

to reproduce:

1. Delete porcupine directory on your host in the selected profile (i.e. ~/rhasspy/profiles/en/porcupine)

2. Deploy new Rhasspy Docker 2.4.20

3. After Rhasspy start got to web page

4. Pop appears on web:
```
    “missing”:
    “/profiles/en/porcupine/libpv_porcupine.so”:
    0: “wake.system”
    1: “porcupine”

    “/profiles/en/porcupine/porcupine.ppn”:
    0: “wake.system”
    1: “porcupine”

    “/profiles/en/porcupine/porcupine_params.pv”:
    0: “wake.system”
    1: “porcupine”
```
- in addition no error is displayed at Rhasspy icon at left top. (probably due to change in 2.4.20: Don't error out on missing porcupine files)

- When click on 'Download now' no output is shown in the text filed in pop-up window, instead immediately another pop-up window appears:

`Download is complete. Rhasspy will now restart. Make sure to train before using your profile! `

5. After Rhasspy restart web pop-up window as described at 4. appears again.

Expected results:
There is directory  ~/rhasspy/profiles/en/porcupine containing files: libpv_porcupine.so, porcupine.ppn, porcupine_params.pv

Current result:
porcupine directory is created but it is empty - i.e. no files are downloaded and extracted there.

Kind regards
litin

**Comment by synesthesiam** [comment]
I'm pushing a new rebuild of 2.4.20, so perhaps that will fix things (watch for Hass.io add-on 2.4.20.1).

Can anyone with more Hass.io knowledge comment here? It seems like they've changed the behavior of writing to `/share` or something.

**Comment by litinoveweedle** [comment]
hello synesthesiam,
thank you, I know about problem with starting hassio addon, but my reported problem is with plain Rhasspy Docker 'synesthesiam/rhasspy-server:latest'

I do run both hassio Rhasspy addon (as my server) and Rhasspy Docker on my clients. The problem I described was found on clients, as my server do not need wake up word.

**Comment by synesthesiam** [comment]
Ah, thanks for the clarification. Let me check it out.

**Comment by synesthesiam** [comment]
I'm getting SSL verification errors on my Pi 3 now with the 2.4.20 Docker image, so nothing is downloading now. This is the **exact** same Dockerfile as used on the x86_64, which works perfectly. Grrrrr....

**Comment by litinoveweedle** [comment]
Hello,
my platform is as well Rpi 3B. Maybe different trusted CA certs? /etc/ssl/certs

**Comment by litinoveweedle** [comment]
I can confirm, that latest Docker image 2.4.20 works OK. Thank you for quick fix. :-)
