### ISSUE TITLE
WebrtcvadCommandListener triggers on beep_hi.wav playing

### ISSUE THREAD

**Issue by iovsiann** [synesthesiam/rhasspy-hassio-addon#223]
Not a serious issue, but FYI. I needed to disable rhasspy beeps (by configuring rhasspy to play a silent wav instead of beep_hi/lo/error.wav). When I configured rhasspy to play a silent wav instead of beep_hi.wav rhasspy behavior has changed - specifically, after me saying wake work rhasspy waits a long time (30 sec) listening for the intent phrase, until it times out. In the original configuration, with beep_hi.wav playing, rhasspy listens for the intent phrase only for a couple of seconds before it times out.

It seems that rhasspy playing beep_hi.wav (upon detecting the wake word) triggers WebrtcvadCommandListener into hearing "voice". When the silent wav plays instead of beep_hi.wav, WebrtcvadCommandListener keeps hearing silence until it times out after 30 sec.

**Comment by synesthesiam** [comment]
Try changing the value of `command.webrtcvad.throwaway_buffers` in your profile JSON. The default is 10, but increasing it will cause Rhasspy to skip more audio before listening.

Also, consider upgrading to 2.5 which has a better way to handle this problem :)
