### ISSUE TITLE
Marytts instructions return exec error

### ISSUE THREAD

**Issue by RidaAyed** [synesthesiam/rhasspy-hassio-addon#224]
Following the instructions given here https://rhasspy.readthedocs.io/en/latest/text-to-speech/#marytts

`docker run -it -p 59125:59125 synesthesiam/marytts:5.2`

Outputs:

```
standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size
```
Env:

    Raspberry Pi 3 Model B Plus Rev 1.3\0 
    4.19.66-v7+

**Comment by koenvervloesem** [comment]
"exec format error" means that the container is built for another architecture. If you look at [the tags of the image on Docker Hub](https://hub.docker.com/r/synesthesiam/marytts/tags), I only see `linux/amd64`, so this won't work on a Raspberry Pi.

**Comment by synesthesiam** [comment]
The image on Docker Hub now supports ARM v7 and ARM 64 (Rpi 2/3/4) :)
