### ISSUE TITLE
Multiple microphones and differ human voices

### ISSUE THREAD

**Issue by FelixWeichselgartner** [synesthesiam/rhasspy-hassio-addon#226]
Hi,

I'm trying to automate my house and want to use rhasspy as a voice assistant. 

I want to have a mic in every room and therefore I need the option to use multiple microphones as inputs. However, I did not find this option in the settings or elsewhere on the internet. 

Furthermore, I could not find any information how I could differ human voices, i.e. the system recognizes who I is speaking and adjusts the output respectively.

TY for any answers.
Have a nice day!

**Comment by synesthesiam** [comment]
Speaker recognition would be a welcome addition to Rhasspy, but is not currently implemented by any of the speech to text systems. Kaldi's [x-vectors](https://www.danielpovey.com/files/2018_icassp_xvectors.pdf) are probably our best shot. Not something I've had time for, unfortunately :/
