### ISSUE TITLE
wake word issue

### ISSUE THREAD

**Issue by chrisfaig** [synesthesiam/rhasspy-hassio-addon#238]
Im having issue to detect the wake work (porcupine Works), but no other.
I testes with respeaker 4 mic array, rspeaker 2 mic, and matrix voice.

Same thing with raspberry 4 (2gb) and raspberry pi 3

Using the latest version of raspian.

Any tips or advise?

**Comment by synesthesiam** [comment]
Please consider upgrading to Rhasspy 2.5 and trying out Mycroft Precise or snowboy. Most of my testing has been going towards Precise.
