### ISSUE TITLE
Mixed Language Model Causing STT to fail

### ISSUE THREAD

**Issue by athanasiusuk** [synesthesiam/rhasspy-hassio-addon#241]
Replicated this on two installs. Whenever the mix ratio is above 0 on either pocketsphinx or kaldi then STT and therefore intent recognition fails. Retraining/restarting does not solve the issue. I notice that whilst the log shows no errors it feels like training is not successful as I don’t get the training duration note.  Recordings happening fine. Is this a known issue?

**Comment by synesthesiam** [comment]
Please try upgrading to 2.5 and see if the issue persists. Mixed modeling hasn't been thoroughly tested on 2.4 in a while.
