### ISSUE TITLE
Speech to text nl_pocketsphinx download error.

### ISSUE THREAD

**Issue by Giel538** [synesthesiam/rhasspy-hassio-addon#243]
This is my first installation. Version 2.5 running in docker on a rpi4

I followed the guide and chose pocketsphinx for speech to text. But when i download the files i get this error.

DownloadFailedException: ('https://github.com/synesthesiam/nl_pocketsphinx-cmu/raw/master/g2p.fst/g2p.fst.gz.part-03', 'Part size mismatch (got 170730 byte(s), expected 26214400)')

DownloadFailedException: ('https://github.com/synesthesiam/nl_pocketsphinx-cmu/raw/master/g2p.fst/g2p.fst.gz.part-02', 'Part size mismatch (got 170730 byte(s), expected 26214400)')

Looks like the file is not there or moved?

When i set my profile to English i am been able to download the package.

**Comment by Giel538** [comment]
This is the file (g2p.fst) which comes from the json string when i press on (9 missing files 318mb)

    "nl_pocketsphinx-cmu/g2p.fst": {
        "bytes_expected": 379247251,
        "file_key": "nl_pocketsphinx-cmu/g2p.fst",
        "file_path": "/profiles/nl/g2p.fst",
        "human_size": "361.7 MiB",
        "setting_name": "speech_to_text.system",
        "setting_value": "pocketsphinx",
        "index": 8
    }
}

**Comment by synesthesiam** [comment]
If you can, please upgrade to Rhasspy 2.5. The problem has been fixed there.
