### ISSUE TITLE
MyCroft precise in 2.5.1 (debian install)

### ISSUE THREAD

**Issue by patrickjane** [synesthesiam/rhasspy-hassio-addon#249]
My profile is the same as in 2.4, where I have:

```
    "wake": {
      "system": "precise",
      "precise": {
        "model": "precise/hey-mycroft.pb",
        "sensitivity": 0.5,
        "trigger_level": 3,
        "chunk_size": 2048
      }
    },
```

Now the debian package installation of rhasspy 2.5.1 seems to search in a different place for the model file:
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/rhasspy/rhasspy/rhasspywake_precise_hermes/models/precise/hey-mycroft.pb'
```

The above error can be fixed by using an absolute path in the `profile.json`, however precise itself does not seem to work. When saying "Hey mycroft", I hear no confirmation beep, and successive utterances are not recognized. All I see in the logs is:

```
[DEBUG:2020-07-18 20:48:18,308] rhasspywake_precise_hermes: -> HotwordDetected(model_id='hey-mycroft.pb', model_version='', model_type='personal', current_sensitivity=0.5, site_id='default', session_id=None, send_audio_captured=None, lang=None)
[DEBUG:2020-07-18 20:48:18,308] rhasspywake_precise_hermes: Publishing 182 bytes(s) to hermes/hotword/hey-mycroft/detected
[DEBUG:2020-07-18 20:48:18,322] rhasspyserver_hermes: <- HotwordDetected(model_id='hey-mycroft.pb', model_version='', model_type='personal', current_sensitivity=0.5, site_id='default', session_id=None, send_audio_captured=None, lang=None)
```

Is precise broken in 2.5?

**Comment by synesthesiam** [comment]
Precise should be working fine in 2.5. Have you set "Rhasspy" as the dialogue manager? That needs to be running for the beeps to sound and for the ASR/NLU systems to be engaged after a hotword is detected.

**Comment by patrickjane** [comment]
Yes, actually this solved the problem.
