### ISSUE TITLE
Installation on virtual environment fails for latest raspbian (buster)

### ISSUE THREAD

**Issue by jrhbcn** [synesthesiam/rhasspy-hassio-addon#26]
Hi, 

Trying to install rhasspy on a clean raspbian buster lite fails with (virtualenv method):

`pi@raspberrypi:~/rhasspy $ ./download-dependencies.sh
Downloading /home/pi/rhasspy/download/rhasspy-tools_amd64.tar.gz (https://github.com/synesthesiam/rhasspy/releases/download/v2.0/rhasspy-tools_amd64.tar.gz)
Downloading /home/pi/rhasspy/download/rhasspy-tools_armhf.tar.gz (https://github.com/synesthesiam/rhasspy/releases/download/v2.0/rhasspy-tools_armhf.tar.gz)
Downloading /home/pi/rhasspy/download/rhasspy-tools_aarch64.tar.gz (https://github.com/synesthesiam/rhasspy/releases/download/v2.0/rhasspy-tools_aarch64.tar.gz)
curl: (22) The requested URL returned error: 404 Not Found
` 
Any workaround? Thanks,

**Comment by synesthesiam** [comment]
Sorry to take so long to address this! It was a silly mistake; I uploaded the file with a `_arm64` ending instead of `_aarch64`. I've re-named the file, so you should be able to just re-run `download-dependencies.sh` and have it work. Please let me know if there are any more problems.
