### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by JohnDorien1** [synesthesiam/rhasspy-hassio-addon#35]
Trying to get this running on a pi.

running ./run-venv.sh throws an error:
`./run-venv.sh: line 28:   916 Illegal instruction     python3 app.py`

doing python3 app.py manually gives:
```
  File "app.py", line 838
    ws_queues:List[Dict[Any, GQueue]] = [{}, {}]
             ^
SyntaxError: invalid syntax
```

Any idea how to solve this? As I cannot find this issue reported anywhere it looks like a system related issue?

**Comment by synesthesiam** [comment]
Are you trying to install in Python 3.5?

**Comment by JohnDorien1** [comment]
Clean raspbian then install scripts. So should be in 3.5? Checking for manual install gives 3.5 is installed properly

**Comment by koenvervloesem** [comment]
Raspbian Buster should have Python 3.7:

```
pi@rpi3:~ $ cat /etc/debian_version 
10.1
pi@rpi3:~ $ python3 --version
Python 3.7.3
```

**Comment by synesthesiam** [comment]
Rhasspy needs at least Python 3.6 for type annotations.
