### ISSUE TITLE
Some profiles missing in docker latest image 

### ISSUE THREAD

**Issue by aserramonner** [synesthesiam/rhasspy-hassio-addon#36]
Attempting to run docker image with catalan profile:

$ docker run -d -p 12101:12101       --restart unless-stopped       -v "$HOME/.config/rhasspy/profiles:/profiles"       synesthesiam/rhasspy-server:latest       --user-profiles /profiles       --profile ca

Gives the following error:

Traceback (most recent call last):
  File "app.py", line 910, in <module>
    start_rhasspy()
  File "app.py", line 135, in start_rhasspy
    args.profile, system_profiles_dir, user_profiles_dir, actor_system=system
  File "/usr/share/rhasspy/rhasspy/core.py", line 75, in __init__
    self.profile_name, system_profiles_dir, user_profiles_dir
  File "/usr/share/rhasspy/rhasspy/profiles.py", line 30, in __init__
    self.load_profile()
  File "/usr/share/rhasspy/rhasspy/profiles.py", line 68, in load_profile
    with open(system_profile_path, "r") as system_profile_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/rhasspy/profiles/ca/profile.json'

Doing:

docker container exec e0d5ce05f34d ls /usr/share/rhasspy/profiles/

When the container is running with the 'en' profile, lists the following:

de
defaults.json
el
en
es
fr
hi
it
nl
pt
ru
sv
vi
zh

But I see the 'ca' profile in github, so I guess it is missing in the docker image.

**Comment by synesthesiam** [comment]
I mistakenly left these files out. Thanks for catching it. I'll push them out in the next update.
