### ISSUE TITLE
[Feature] Support for dynamic vocabulary using entities injection

### ISSUE THREAD

**Issue by nanosonde** [synesthesiam/rhasspy-hassio-addon#38]
https://docs.snips.ai/articles/platform/nlu/dynamic-vocabulary

> The vocabulary supported by the ASR and the NLU is limited to the words it has seen at training time (i.e. words that were present in your assistant when it was downloaded). For various reasons, you may want to inject new values to your assistant without having to go through the console. Sensitive information, such as contact names, or other personal details that you want your assistant to understand, are better kept private. It can also be tedious to download again an assistant each time you want to update its vocabulary.
> For these reasons, we are introducing a new feature, Entities Injection, which allows you to update both the ASR and the NLU models directly on the device.
> Each intent within an assistant may contain some slots, and each slot has a specific type that we call an entity. If you have a contact_name entity that contains a list of contacts in an address book, Entities Injection lets you add new contact names to this list.

Required by this Snips skill: https://github.com/Alpha200/snips-openhab
https://snips-openhab.readthedocs.io/de/latest/basics/introduction.html

This skill uses the sementic tagging of OpenHAB and automatically adds vocabulary to Snips for ASR and NLU:
https://community.openhab.org/t/habot-walkthrough-2-n-semantic-tagging-item-resolving/55651

**Comment by synesthesiam** [comment]
Hi @nanosonde. Are you the author of any of these skills or plugins?

Rhasspy can do dynamic vocabulary with the `/api/slots` endpoint. If you POST JSON to it, you can either update or overwrite [slot lists](https://rhasspy.readthedocs.io/en/latest/training/#slots-lists). Something like:

```json
{ "colors": ["red", "green", "blue"] }
```

With an `?overwrite_all=true` query parameter, this will delete any previous `colors` slots first.

After changing slot values, make sure to re-train (e.g., POST to `/api/train`).

**Comment by nanosonde** [comment]
No I am not the developer, but I dived into the snips-openhab skill as I am a user of it.

Would this also work with a lot of words?
Think of a skill which needs to train all the interprets and song names.
