### ISSUE TITLE
[Feature] Support for slot value synonyms

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#39]
Hi!
Congrats for this awesome piece of software.
Great work!

I've been searching for more open source alternatives to Snips since the Sonos acquisition as the future of the Snips platform for makers is looking quite grim... Rhasspy looks pretty good :)

One thing that is really missing is the ability to use synonyms for slot values.

Is it possible or do I have to use multiple slot lists (one for each value with synonyms)?

Cheers.

**Comment by synesthesiam** [comment]
Hi @mathquis, thanks! I'm interested to see how Rhasspy can grow to help those who want a fully open source voice assistant :)

You should be able to get slot value synonyms by using substitutions in your slot values. If you have something like this in a `colors` slot:

```
red
rouge:red
```

then saying either "red" or "rouge" will result in "red" going into the recognized intent.

**Comment by mathquis** [comment]
Thanks :)
It kind of works.
The value is not correctly flagged though.

Example:
Slot list `music-type` containing:
```
the last album:last
the first album:first
```
Intent: `play $(music-type){type}`
Utterance: `play the last album`

The intent is correctly recognized but the `type` slot value is incorrect as I get `the last **last**`.

Looks like a white space issue.

**Comment by mathquis** [comment]
Seems the substitution only take the word before the `:` and replace it with the word after the `:`.

How can I substitute multiple words as one?

I tried using parenthesis like `(the last album):last` or double quotes like `"the last album":last` but I get a training error.

**Comment by synesthesiam** [comment]
Sorry for the lack of documentation here. The way to do this is using empty substitutions for the words you want dropped:

```
the: last: album:last
the: first: album:first
```

This will drop "the", "last", and "first". You can also just write this as:

```
the: last album:
the: first album:
```

You can also add words with something like (`:word1 :word2`) so `word1` and `word2` will show up regardless of what's spoken. In the future, I'd like to support the parenthesis substitution you mentioned.

**Comment by mathquis** [comment]
Thanks for the feedback.

I tested and it works but leaves remaining white spaces like `the: first: album:first` becomes `_first`.

The syntax becomes pretty unreadable so using parenthesis substitution would indeed be much clearer and should allow variations (like synonyms) of the same value using `|` on the same line.

Looking forward to it ;)

Great job!
