### ISSUE TITLE
[Feature] Support slot types

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#40]
How can we handle slot types similar to Snips' ?

- number
- percent
- date, time and datetime
- duration
- temperature
- ordinal

**Comment by synesthesiam** [comment]
This would be very useful, but is currently not supported. Rhasspy supports more languages than Snips, so getting these slot types working for all of them may not be possible (which is OK).

If I add this to Rhasspy, I would want to have the user specify ranges. Snips is probably doing something much more sophisticated than Rhasspy, so it can support very large number/date ranges. But Rhasspy will have very poor performance if I don't ask the user to restrict them to only what's expected.

What do you think?

**Comment by koenvervloesem** [comment]
Snips entity extraction (and hence slot types) is based on [Duckling](https://duckling.wit.ai/).

**Comment by mathquis** [comment]
The Snips NLU engine is open-source and available here:
https://github.com/snipsco/snips-nlu

It handle training from JSON/YAML, built-in slot types (based on Rustling a Rust version of Duckling), support lots of languages (de, en, es, fr, it, ja, ko, pt) and is written in Python (and Rust).

Maybe it can be integrated directly in Rhasspy?

With a library like [python-duckling](https://github.com/FraBle/python-duckling), it should be possible to parse these slot types using special "Slots Lists" like `($rhasspy/datetime){when}`.

This will greatly simplify the creation of actionable intents.

What do you think?

**Comment by synesthesiam** [comment]
The parsing looks straightforward with this library, but what about generating the proper voice commands? Rhasspy works by transforming your voice command grammar into a language model that contains the statistics for all possible spoken sentences. Anything outside this set of sentences won't be recognized by the speech to text system.

I'm not sure hows the Snips folks got around this issue, but I do know Rhasspy's performance degrades as you increase the number of possible sentences. So we should come up with a way for users to specify the precise number/date ranges they plan to speak, and then we could use the `duckling` library for parsing.

**Comment by koenvervloesem** [comment]
Another interesting project: Mycroft's [Lingua Franca](https://mycroft.ai/blog/lingua-franca-v0-1-released/).

**Comment by KiboOst** [comment]
Yes, such slots, like duration, is a must have.
"Remind me in x minutes to ..."
"Let the lights in living room on for x minutes"
etc
Use them a lot with snips/jeedom and can't see how to have a solution without at least duration, datetime and percentage

**Comment by synesthesiam** [comment]
Work for this will move to https://github.com/rhasspy/rhasspy-asr-kaldi
