### ISSUE TITLE
Support For Alternatives when using Tag Synonyms

### ISSUE THREAD

**Issue by keassol** [synesthesiam/rhasspy-hassio-addon#42]
First off, cant thank you enough.  Been migrating from snips this weekend (sonos thing) and so far Rhasspy is super great.

I may be misunderstanding something but it appears that Alternatives do not work when using Tag Synonyms.  I have a room that some people refer to as "den" and some people refer to as "playroom" For instance, both of these Sentences works:
```
toggle [the] den [light] {light_name:den_overhead}
toggle [the] playroom [light] {light_name:den_overhead}
```

However this one does not:

`toggle [the] (den | playroom) [light] {light_name:den_overhead}`

Obviously they both accomplish the same thing but for simplicity sake and since people often have rooms/switches/areas that have multiple names it would be nice to create the one liner Sentences. 

**More detail:**

for
`toggle [the] playroom [light] {light_name:den_overhead}`
output is:

> Raw Intent JSON
> "intent":
> "entities":
> 0:
> "end": 23
> "entity": "light_name"
> "raw_end": 20
> "raw_start": 11
> "raw_value": "den light"
> "start": 11
> "value": "den_overhead"
> "hass_event":
> "event_data":
> "light_name": "den_overhead"
> "event_type": "rhasspy_DoToggleLight"
> "intent":
> "confidence": 1
> "name": "DoToggleLight"
> "intents":
> "raw_text": "toggle the den light"
> "raw_tokens":
> 0: "toggle"
> 1: "the"
> 2: "den"
> 3: "light"
> "slots":
> "light_name": "den_overhead"
> "speech_confidence": 1
> "text": "toggle the den_overhead"
> "time_sec": 0.021739721298217773
> "tokens":
> 0: "toggle"
> 1: "the"
> 2: "den_overhead"

but for:
`toggle [the] (den | playroom) [light] {light_name:den_overhead}`
output is:  

> Raw Intent JSON
> "intent":
> "entities":
> 0:
> "end": 25
> "entity": "light_name"
> "raw_end": 20
> "raw_start": 11
> "raw_value": "den light"
> "start": 11
> "value": ": den_overhead"
> "hass_event":
> "event_data":
> "light_name": ": den_overhead"
> "event_type": "rhasspy_DoToggleLight"
> "intent":
> "confidence": 1
> "name": "DoToggleLight"
> "intents":
> "raw_text": "toggle the den light"
> "raw_tokens":
> 0: "toggle"
> 1: "the"
> 2: "den"
> 3: "light"
> "slots":
> "light_name": ": den_overhead"
> "speech_confidence": 1
> "text": "toggle the : den_overhead"
> "time_sec": 0.028543949127197266
> "tokens":
> 0: "toggle"
> 1: "the"
> 2: ":"
> 3: "den_overhead"

**Comment by synesthesiam** [comment]
Thanks for catching this. I'm looking into a fix now.

**Comment by synesthesiam** [comment]
Should be fixed in the latest version.
