### ISSUE TITLE
Support for slots aliases

### ISSUE THREAD

**Issue by keassol** [synesthesiam/rhasspy-hassio-addon#43]
Maybe this is a stretch but it would be helpful to have support for a slots aliases file.  Given this slots file:

`{"light": ["familyroom_overhead","den_overhead"]}`

if there was a slots aliases file of:

`{"familyroom_overhead": ["family room overhead", "family room", "living room overhead", "living room"],"den_overhead": ["den overhead","den","playroom overhead","playroom"]}`

then I could reduce this:

```
[DoToggleLight]
toggle [the] (kitchen) [light] {light_name:kitchen_overhead}
toggle [the] den [light] {light_name:den_overhead}
toggle [the] playroom [light] {light_name:den_overhead}
toggle [the] play room [light] {light_name:den_overhead}
toggle [the] (entry way) [light] {light_name:entry_way}
toggle [the] (family room) [light] {light_name:familyroom_overhead}
etc...
```
to this:

```
[DoToggleLight]
light_name = $light {light_name}
toggle [the] <light_name>
```

The above is just a lights example but it seems also useful for running scripts using multiple names.  For example  ["everyone is leaving","were leaving now", "see ya later rhasspy", "I'm off now", etc] can be aliases for the everyone_is_leaving script in Home Assistant

Maybe there is already a way to do this that I am missing, but if not, I request support for the above if possible.

**Comment by synesthesiam** [comment]
I really need to update the documentation for this :) You can use substitutions in slot files with the colon (`:`). On the left-hand side is what's spoken, and on the right-hand side is what's put into the intent. Either side can be empty, which can be used to drop or add words.

So something like:

```
family: room: overhead: :familyroom_overhead
```
will drop the first 3 words (empty right-hand sides) and add the last word (empty left-hand side). You can combine this with other constructs, like optionals and alternatives:

```
(den: | playroom:) [overhead:] :den_overhead
```
which should work for "den overhead", "den", "playroom", and "playroom overhead".

So your example would be:

```
{"light": ["family: room: [overhead:] :familyroom_overhead", "(den: | playroom:) [overhead:] :den_overhead"]}
```

**Comment by keassol** [comment]
Yep.  That did the trick.  Thank you very much!

In the end, I went with these sentences:
```
[DoToggleSwitch]
switch_name = $switch {switch_name}
toggle [the] <switch_name> [room] [light] [switch]
```
with these slots:
```
{
    "switch": [
        "(family: | living:) :familyroom_overhead",
        "(den: | playroom:) :den_overhead",
        "(back: porch: rope: light: | east: porch: | back: porch: east: | back: porch: dimmer:) :back_porch_dimmer",
        "(bedroom: lamp: | lamp: in: bedroom: | nightstand:) :bedroom_lamp",
        "(fireplace: light: | fireplace: color: bulb: | fireplace: bulb:) :fireplace_light",
        "(kitchen: overhead: | kitchen: main: | kitchen:) :kitchen_overhead",
        "(dining: room: | dining: area: | home: school:) :dining_room_overhead"
    ]
}
```
and that seems to work pretty well.  I still think it would be beneficial to have the slots aliases array as it can potentially simplify peoples config files.

Thanks for your great project!
