### ISSUE TITLE
Kaldi installation (profile de) does not install required files

### ISSUE THREAD

**Issue by nanosonde** [synesthesiam/rhasspy-hassio-addon#44]
Hi!

I just did a clean install of rhasspy docker image and selected profile "de" during installation.
It seems that the later Kaldi installation has issues.

I had to basically copy the contents of https://github.com/synesthesiam/rhasspy/tree/master/profiles/de/kaldi manually into ~/.config/rhasspy/profiles/de/kaldi.

Without this, training did not succeed and complained about missing "HCLG.fst".
So I stumbled accross the same issue as someone else described here: https://community.home-assistant.io/t/rhasspy-offline-voice-assistant-toolkit/60862/901

**Comment by synesthesiam** [comment]
Thanks for catching this. I was failing to copy the files into the `kaldi` directories under each profile, and instead actually overwriting the main files!

**Comment by DeadEnded** [comment]
still having issues with this on EN language.
I copied to files explained above... deleted my container and image and started from scratch... still getting the missing HCLG.fst.

**Comment by synesthesiam** [comment]
Ok, please give it another try. After switching to Kaldi, make sure to train and then restart Rhasspy. I had a successful test with a clean install on en, de, and nl.

**Comment by DeadEnded** [comment]
Okay, thanks for the help.
I downloaded the newest image, and cleared my configuration folders.
Created a new container, and now Kaldi appears to be working.

Now on to getting Rasa NLU to work... I am trying to test all variations, then pick one :-).

Thanks again!
DeadEnd
