### ISSUE TITLE
Support for TTS via Hermes/MQTT

### ISSUE THREAD

**Issue by nanosonde** [synesthesiam/rhasspy-hassio-addon#45]
It would be nice if rhasspy could also use Hermes protocol for speaking text.

Actual use-case for me would be the usage of AWS Polly for TTS.
The Python script below listens for Hermes TTS "say" command plays the returned "WAV" data via Hermes Audio Server protocol:
https://github.com/hcooper/snips-tts-polly 

-    subscribes to `hermes/tts/say` to pick up new TTS requests.
-    sends converted audio to `hermes/audioServer/default/playBytes`.
-    closes Snips session via `hermes/tts/sayFinished`.

The above script also caches already generated WAVs.

**Comment by synesthesiam** [comment]
Not sure if this is exactly what you mean, but Rhasspy will handle the `playBytes` message if you set the [audio output to Hermes](https://rhasspy.readthedocs.io/en/latest/audio-output/#mqtthermes).

**Comment by nanosonde** [comment]
Somehow I am still attracted by the idea of having each step of the (Snips) processing pipeline available via MQTT(Hermes).
For now I could reuse the snips-dialogue-manager which required the „low-level“ Hermes TTS API until a replacement was found. 

But you are right:intent handling should not be part of rhasspy which my idea would imply.
