### ISSUE TITLE
Virtual environment installation fails

### ISSUE THREAD

**Issue by Santobert** [synesthesiam/rhasspy-hassio-addon#47]
The script `download-dependencies.sh` fails with the following error:
```
download-dependencies.sh: Zeile 73: CPU_TO_FRIENDLY: Falscher Feldbezeichner.
```

It's german, sorry. The error occurs in line 73. `CPU_TO_FRIENDLY` seems wrong here.

Additional:
Arch Linux with Kernel 5.3.12-arch1-1
Bash: `GNU bash, Version 5.0.11(1)-release (x86_64-pc-linux-gnu)`

Is Arch Linux supported? If not, is there a manual for generic Linux for installing rhasspy?

**Comment by synesthesiam** [comment]
What does the following command return on your machine?

```
lscpu | awk '/^Architecture/{print $2}'
```

This is what I'm using to get the CPU architecture (x86_64, arm7vl, or arm64v8). I've also just added a `--cpu-arch` flag to `download-dependencies.sh` so you can override the detected architecture if necessary.

**Comment by Santobert** [comment]
Hm... it returns nothing. My setup is german so the correct command would be 
```bash
lscpu | awk '/^Architektur/{print $2}'
```

Maybe `uname --m` would be better to determine the CPU architecture.

**Comment by synesthesiam** [comment]
Well, this is embarrassing for a supposedly multi-language project! I've updated the scripts to use `uname` instead. Thank you :)
