### ISSUE TITLE
Support for receiving from / sending to multiple site ids

### ISSUE THREAD

**Issue by Red5d** [synesthesiam/rhasspy-hassio-addon#49]
Is it possible to have Rhasspy listen for Hermes data from multiple different site ids and pass the received site id through to the intent object so it could then be used in a direct (Hermes TTS) response back to that site? 

This would enable using multiple individually-addressable "satellites" and not have response audio go back to all sites, just the one that is being actively used.

**Comment by synesthesiam** [comment]
This is possible, but will require a few changes to the Hermes audio recorder. I will need to keep separate audio buffers for each site id, and thread that id through the speech and intent recognition processes.

**Comment by asktimfisher** [comment]
I am also very interested in having this capability!

**Comment by raufis27** [comment]
Please add this function, so we can use existing snips satellites. Thank you!

**Comment by legomind** [comment]
This is the only missing feature that is holding me back from dumping google home.

**Comment by koenvervloesem** [comment]
This is probably the number one missing feature for a lot of people, including me :-) This is work in progress and was one of the reasons for Michael's big rewrite of Rhasspy into various independent services, which is going on [in the rhasspy organization](https://github.com/rhasspy/). So stay tuned!

**Comment by synesthesiam** [comment]
This is now being tested in the 2.5 pre-release :)
