### ISSUE TITLE
DeepSpeech support

### ISSUE THREAD

**Issue by synesthesiam** [synesthesiam/rhasspy-hassio-addon#50]
In light of [DeepSpeech 0.6](https://hacks.mozilla.org/2019/12/deepspeech-0-6-mozillas-speech-to-text-engine/) being released today, I'd like to try and add support for DeepSpeech as an alternative speech to text engine in Rhasspy.

**Comment by nanosonde** [comment]
Maybe this is interesting for you:
https://github.com/AASHISHAG/deepspeech-german

Does not only use Mozilla CV, but also other German datasets.

**Comment by synesthesiam** [comment]
Thank you, I took a look. The German model is built for DeepSpeech 0.5, so I will need to find a way to have both versions installed.

If anyone finds DeepSpeech models for other languages, please post links here!

**Comment by nanosonde** [comment]
A new German model for deepspeech-0.6.0 is on their ToDo list: https://github.com/AASHISHAG/deepspeech-german/issues/3

**Comment by synesthesiam** [comment]
Feature request moved to https://community.rhasspy.org/t/deepspeech-and-tts-from-mozilla/46/2
