### ISSUE TITLE
Node-Red send text to Rhasspy to play (feature request)

### ISSUE THREAD

**Issue by prabbit237** [synesthesiam/rhasspy-hassio-addon#52]
I'm not sure if this already exists and I'm just not seeing it or exactly what the case is but........

Is there a way that you can "push" text to Rhasspy to have it speak it? I.e. I know you can do the following:

1) Say something to Rhasspy.
2) send an intent back to HomeAssistant or Node-Red.
3) Say something back to the user like "OK" or "It's not responding", etc.

But what about Node-Red seeing there's a timer that's up and it needs to send out "You have a doctor's appt in 1 hour" to all Rhasspy devices. Can Node-Red send some sort of a MQTT or an API  call that one (or all) devices will get that will make them say something out of the blue?

**Comment by richardmward** [comment]
I believe you just post to it's REST API, as per: https://rhasspy.readthedocs.io/en/latest/usage/#http-api. The payload is defined in: https://github.com/synesthesiam/rhasspy/blob/master/public/swagger.yaml

**Comment by prabbit237** [comment]
> 
> 
> I believe you just post to it's REST API, as per: https://rhasspy.readthedocs.io/en/latest/usage/#http-api. The payload is defined in: https://github.com/synesthesiam/rhasspy/blob/master/public/swagger.yaml

Ok, yeah, du-uh... It was late and I was tired (that's my story and I'm sticking to it.) I was looking for an MQTT way of doing it and wasn't even thinking that the web UI does it via HTTP so anything else that can also send HTTP (such as Node-Red) can also push text to it.
