### ISSUE TITLE
Adding a websocket event for wake word

### ISSUE THREAD

**Issue by Hermitter** [synesthesiam/rhasspy-hassio-addon#53]
Hey! Would you consider adding a new WebSocket event called `/api/events/wakeword`. This would allow users to trigger LEDs for visual confirmation that Rhasspy is listening. It seems that the only way to react to a wake word event is by parsing the logs in `/api/events/log` which isn't an ideal solution.

**Comment by synesthesiam** [comment]
Hi! Let me give this some thought. I definitely agree that all of Rhasspy's events should be available over websocket too.

In the mean time, if you have access to MQTT, you can listen to `rhasspy/en/transition/#` (for the "en" profile) to watch as the sub-components of Rhasspy switch states. The wake word listener you have configured will be in there (maybe `PorcupineWakeListener`), and it will switch between a `listening` and `started` state.

**Comment by Hermitter** [comment]
Oh nice, I didn't realize there were other MQTT topics I could subscribe to. Thanks for considering this!

**Comment by KiboOst** [comment]
Have a look here:
https://github.com/Psychokiller1888/snipsLedControl

Would absolutely rocks to have such led control with rhasspy ! This make a visual state of our assistant and help a lot in day to day interaction with it.

**Comment by KiboOst** [comment]
Could also add a remote post to a server when a wakeword is detected with wakeword I’d and site id. 
This would allow more control on jeedom plugin for example, to mute music when wakeword is detected and such things.

**Comment by synesthesiam** [comment]
See also for a intermediary solution: https://community.rhasspy.org/t/intent-handling-remote-publish-wakeword-detected/125/13

**Comment by synesthesiam** [comment]
This will be added in 2.4.18 as `/api/events/wake`

**Comment by KiboOst** [comment]
Don't waste your time, we are waiting v2.5 :-)))

**Comment by synesthesiam** [comment]
Added in 2.4.18
