### ISSUE TITLE
Google AIY Voice Hat for microphone?

### ISSUE THREAD

**Issue by ocdtrekkie** [synesthesiam/rhasspy-hassio-addon#54]
Have you played with or know the success of using Google AIY Voice Kits with Rhasspy? You get all the parts sans the Pi for a little voice assistant doodad, including a two-mic array.

Micro Center has been clearing out a massive number of the original AIY Voice Kit for $2.99 for a while, and I bought like... five or six, I think: https://www.microcenter.com/product/483414/google-aiy-voice-kit

I know Snips.ai worked with the Voice Kit hardware: https://medium.com/snips-ai/is-it-google-aiy-nah-its-snips-f67c9dc2139a

**Comment by synesthesiam** [comment]
No, I'd never heard of them. It's a shame the nearest store with them in stock is so far away from me! It should work just fine with Rhasspy if you can detect the microphone using `arecord -L` on your Pi.

I have heard people not able to get the Docker images running on a Pi Zero, though. I know those use the original ARM process from the Pi, which must not be an ARMv7? I haven't checked around yet for compatible Docker base images that I could use to build for the Zero (I use qemu inside Docker to build for `armhf` and `aarch64`.

**Comment by ocdtrekkie** [comment]
The original Voice Kit I have a stack of was intended with the full-size Pi in mind, so I figured I'd probably end up using a 3 B+ as recommended for any such attempt. I know the newer Voice Kit includes a Zero (and is in the form of a Bonnet and not a Hat.)

**Comment by synesthesiam** [comment]
I may have to get one of the newer kits eventually. Please let me know if you end up trying it out with Rhasspy.

**Comment by amadib** [comment]
Don't mean to necro this were you able to get Rhasspy to work @ocdtrekkie ?

This is the error message I receive after "Testing" my speakers. I installed the drivers for the Google AIY voicekit from [here](https://github.com/shivasiddharth/GassistPi). And the mic/speakers are being recognized by the pi just not by Rhasspy. I can open an issue if you prefer.

![IMG_20200319_030055](https://user-images.githubusercontent.com/326888/77040796-0a2a3700-698f-11ea-8dfb-ae74526b7640.jpg)

**Comment by ocdtrekkie** [comment]
I haven't the time to play with this, unfortunately. I'm hoping someone does though!

**Comment by amadib** [comment]
i was your guinea pig and seemed to have hit a wall.
@synesthesiam please advise
