### ISSUE TITLE
Support for NanoTTS?

### ISSUE THREAD

**Issue by flatsiedatsie** [synesthesiam/rhasspy-hassio-addon#55]
Can NanoTTS be used with Rhasspy?

https://github.com/gmn/nanotts

**Comment by synesthesiam** [comment]
Are there any pre-compiled packages for this?

**Comment by flatsiedatsie** [comment]
The Voco add-on, which adds local voice control to the Mozilla WebThings Gateway (which is built on Raspbian), has it built in. 

https://github.com/createcandle/voco/tree/master/snips


Mozilla Gateway Addons are not allowed to install anything onto the system, so this add-on is fully portable. That's why the library files are in the same directory. From memory, I believe the following files there are needed:
```
nanotts
libttspico.so.0
libttspico.so.0.0.0
```

And here you can see a shell script that adds the directory to the path so that the library files are found, and then calls it: https://github.com/createcandle/voco/tree/master/snips

I compiled this version myself following the steps at NanoTTS.

**Comment by synesthesiam** [comment]
Issue moved: https://github.com/rhasspy/rhasspy-tts-cli-hermes/issues/1
