### ISSUE TITLE
Add continuous integration to the repository

### ISSUE THREAD

**Issue by koenvervloesem** [synesthesiam/rhasspy-hassio-addon#57]
It would be nice to have some kind of continuous integration for this repository (and related Rhasspy repositories), so for each commit tests could be run, some basic linting checks could happen, and so on. This would improve code quality and reliability by catching issues as soon as possible.

I'm using Travis CI for my projects, for instance see https://github.com/koenvervloesem/snipskit/blob/master/.travis.yml

You can start with a basic `.travis.yml`, for example like https://github.com/koenvervloesem/snips-app-say-it-again/blob/master/.travis.yml

**Comment by synesthesiam** [comment]
I'd like to add continuous integration as well, but I've wondered if it will be possible to set up the build environment in Travis CI. It looks like the configuration can get pretty complex. so it looks promising.

My first pass would probably be to use the `create-venv.sh` script and then the `run-tests.sh` script. The CI environment would need to download profile files as well, though...

**Comment by synesthesiam** [comment]
Looking into this now.

**Comment by synesthesiam** [comment]
Discussion moved to project: https://github.com/orgs/rhasspy/projects/2
