### ISSUE TITLE
[Feature] Allow splitting sentenses.ini file

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#63]
With lots of intents, the `sentenses.ini` file can get huge and unreadable.

It would be awesome to be able to split it in multiple files.

Why not move the `sentenses.ini` file in a `intents/` folder in the profile and merge all `.ini` files in that folder at training time (like what is done for the slots).

That way we can have one file per intent or per domain if needed.

*Note: This will break the web UI "Sentences" tab. Maybe adding a SELECT to edit each file separately can be a good mitigation.*

**Comment by koenvervloesem** [comment]
This will also make it easier to add the concept of apps/skills to Rhasspy: every app would have its own sentences.ini, and all these files could be merged after installation of extra apps. And when you remove an app, its sentences.ini can be deleted easily without having an impact on the rest of the intents.

**Comment by KiboOst** [comment]
If I set some ini file like myintent.ini with some sentences inside and remove entire content in UI/sentences, I got an error :

> Training failed: Failed to parse sentences 

In console:

```
ERROR:__main__:Training failed: Failed to parse sentences
Traceback (most recent call last):
  File "/home/pi/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/pi/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "app.py", line 579, in api_train
    raise Exception(f"Training failed: {result.reason}")
Exception: Training failed: Failed to parse sentences
```

**Comment by KiboOst** [comment]
also Not sure such separated ini files are taken:

/api/sentences return only the one in sentences tab, not the one in files:

Is format good ?
file: `.config\rhasspy\profiles\fr\intents\lightsSetJeedom.ini`
content:
```
allume la lumière [de | dans] [la | le] ($house_room){house_room}
mets de la lumière dans [la | le] ($house_room){house_room}
```

**Comment by synesthesiam** [comment]
I didn't want to break API compatibility, so `/api/sentences` returns only `sentences.ini` by default as plain text. If you set an `Accept: application/json` header, however, you'll receive JSON like this:

```json
{
  "sentences.ini": "...",
  "intents/lightsSetJeedom.ini": "..."
}
```

**Comment by synesthesiam** [comment]
Same works with POST-ing to `/api/sentences`. Plain text will overwrite `sentences.ini`, while JSON will overwrite multiple files (creating new ones, or deleting ones with empty text).

**Comment by KiboOst** [comment]
No problem ,-)

Any idea why my intents/ini files are not taken ? Should they be ini file like sentences.ini or json files or what ? Any example ?

If I put lightsSetJeedom.ini file into intents with :

```
[lightsSetJeedom]
allume la lumière [de | dans] [la | le] ($house_room){house_room}
mets de la lumière dans [la | le] ($house_room){house_room}
```

When doing a retrain, it crash 

> TaskFailed Command failed: 'ngrammake /home/pi/.config/rhasspy/profiles/fr/intent.fst.counts /home/pi/.config/rhasspy/profiles/fr/intent.fst.model' returned 1 

Slots are defined in intents/slots and show ok in slots tab

**Comment by mathquis** [comment]
The `intents/*.ini` files work fine with the latest docket build (I tested it today). 

Can you try to delete the mentionned `intent.fst.*` files in your profile folder? They should be recreated during the next training.

**Comment by KiboOst** [comment]
Nope, exact same error.
I'm on venv, did a pull deleted venv en recreated it, delete .config/.../intent.fst.*

**Comment by synesthesiam** [comment]
Should be fixed now.
