### ISSUE TITLE
Slot value is not extracted if optional

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#64]
For ASR result:

> read me the hound of the baskervilles in the bedroom

With:
```
[playBook]
read me ($audiobook-book-name){book} ($assistant-zones){zone}
```

I get both `book` and `zone` slot extracted by the NLU.

With 
```
[playBook]
read me ($audiobook-book-name){book} [ ($assistant-zones){zone} ]
```

I get only `book` although `zone` is present.

Hope this helps.

**Comment by synesthesiam** [comment]
Should be fixed in 2.4.13
