### ISSUE TITLE
error when run: python3 -m pip install snowboy-1.3.0.tar.gz

### ISSUE THREAD

**Issue by vinhpaint** [synesthesiam/rhasspy-hassio-addon#7]
(.venv) root@DiskStation:/rhasspy/.venv# python3 -m pip install snowboy-1.3.0.tar.gz
Processing ./snowboy-1.3.0.tar.gz
Requirement already satisfied: PyAudio in ./lib/python3.7/site-packages (from snowboy==1.2.0b1) (0.2.11)
Building wheels for collected packages: snowboy
  Building wheel for snowboy (setup.py) ... error
  Complete output from command /rhasspy/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-dto_0pe5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-e94tpjxi --python-tag cp37:
  running bdist_wheel
  running build
  Compiling snowboy...
  make: python3-config: Command not found
  make: python3-config: Command not found
  swig -I../../ -c++ -python -o snowboy-detect-swig.cc snowboy-detect-swig.i
  g++  -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
  snowboy-detect-swig.cc:176:21: fatal error: Python.h: No such file or directory
   # include <Python.h>
                       ^
  compilation terminated.
  Makefile:70: recipe for target 'snowboy-detect-swig.o' failed
  make: *** [snowboy-detect-swig.o] Error 1
  creating build
  creating build/lib
  creating build/lib/snowboy
  error: can't copy 'swig/Python3/_snowboydetect.so': doesn't exist or not a regular file

  ----------------------------------------
  Failed building wheel for snowboy
  Running setup.py clean for snowboy
Failed to build snowboy
Installing collected packages: snowboy
  Running setup.py install for snowboy ... error
    Complete output from command /rhasspy/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-dto_0pe5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cbnczbhh/install-record.txt --single-version-externally-managed --compile --install-headers /rhasspy/.venv/include/site/python3.7/snowboy:
    running install
    running build
    Compiling snowboy...
    make: python3-config: Command not found
    make: python3-config: Command not found
    g++  -I../../ -O3 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++0x -c snowboy-detect-swig.cc
    snowboy-detect-swig.cc:176:21: fatal error: Python.h: No such file or directory
     # include <Python.h>
                         ^
    compilation terminated.
    Makefile:70: recipe for target 'snowboy-detect-swig.o' failed
    make: *** [snowboy-detect-swig.o] Error 1
    creating build
    creating build/lib
    creating build/lib/snowboy
    error: can't copy 'swig/Python3/_snowboydetect.so': doesn't exist or not a regular file

    ----------------------------------------
Command "/rhasspy/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-dto_0pe5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cbnczbhh/install-record.txt --single-version-externally-managed --compile --install-headers /rhasspy/.venv/include/site/python3.7/snowboy" failed with error code 1 in /tmp/pip-req-build-dto_0pe5/

**Comment by synesthesiam** [comment]
Make sure you have the python3-dev package installed. Usually, it's `sudo apt-get install python3-dev`
