### ISSUE TITLE
Problem during download profile

### ISSUE THREAD

**Issue by ghost** [synesthesiam/rhasspy-hassio-addon#71]
In a docker install, on the download profile page, as soon as I press download now button, it displays a message in red saying
"Compressed file ended before the end-of-stream marker was reached "

Tried on both a desktop and on a raspberry pi, faced the same issue

**Comment by lufiaraujo** [comment]
Had the same issue with the docker installation on a RPi3. It works fine with the Hassio addon installation though.

**Comment by ghost** [comment]
Now, as soon as I open the web interface, it displays this-
" not enough values to unpack (expected 2, got 1) "
And when I click on Download Now, it again says this-
"Compressed file ended before the end-of-stream marker was reached"

**Comment by synesthesiam** [comment]
Hi @Adityakush , do you have any line numbers for the "not enough values" error?

**Comment by ghost** [comment]
No, it just displays this message at the bottom of the web interface, in red color.
" not enough values to unpack (expected 2, got 1) "
Just this line. Nothing else. Sorry, I don,t know much how to find more about the issue.
You can instruct me if you need me to do something

**Comment by synesthesiam** [comment]
Try using the red "Re-Download Profile" button in the Settings tab. This will clear the download cache and start over.

Also, which profile language are you using?

**Comment by ghost** [comment]
Yes, I already tried that many times. But it doesn't seem to download.

**Comment by ghost** [comment]
The profile and everything else is default- en

**Comment by ghost** [comment]
How big is the download actually?? I want to know to estimate the time I'll have to wait before trying again

**Comment by ghost** [comment]
> Try using the red "Re-Download Profile" button in the Settings tab. This will clear the download cache and start over

Did that 3 times. Initially it starts downloading( so it seems monitoring the incoming traffic), but nothing is shown even after 15 minutes, when there is no downloading going on. No progress. On the root webpage it still keeps asking for the download.
Also tried deleting the en folder  and deleting the docker container and running again. But same problem again

**Comment by synesthesiam** [comment]
The files are downloaded [from here on Github](https://github.com/synesthesiam/rhasspy-profiles/releases/tag/v1.0-en). For a default (en) install, it should be:

* [cmusphinx-en-us-5.2.tar.gz](https://github.com/synesthesiam/rhasspy-profiles/releases/download/v1.0-en/cmusphinx-en-us-5.2.tar.gz)
* [en-g2p.tar.gz](https://github.com/synesthesiam/rhasspy-profiles/releases/download/v1.0-en/en-g2p.tar.gz)

There will also be some files downloaded for the Porcupine wake word library, but they're small by comparison. All in all, it's probably around 75 MB?

**Comment by ghost** [comment]
okay. So, do i need to do something after manually downloading them. Or should I just place them into the en directory

**Comment by synesthesiam** [comment]
Put them in en/download. Rhasspy should pick them up from there :)

**Comment by ghost** [comment]
Thanks a lot. I'll check it out tomorrow and let you know.

**Comment by timaschew** [comment]
I have the same problem with a `de` profile using this command to run the container:

Somehow GitHub gave me limited bandwidth because downloading it via the website was also super slow I guess that is the issue. I've downloaded it through my server and it was super fast and copied it manually over and it worked.

**Comment by ghost** [comment]
Hi !
I ssh into the directory
/.config/rhasspy/profiles/en/download
Then downloaded the two files using the following commands

` sudo wget https://github.com/synesthesiam/rhasspy-profiles/releases/download/v1.0-en/cmusphinx-en-us-5.2.tar.gz`
`sudo wget https://github.com/synesthesiam/rhasspy-profiles/releases/download/v1.0-en/en-g2p.tar.gz
`
Restarted the system.
Then opened the the webserver and it still asks to download the files.
What am I missing?
I thing I would like to mention is that I have installed rhasspy  in a docker container.
Any suggestions?
Anything about permissions stuff?
Update:
Okay so clicking Download Now showed the Download Complete message.
Thanks
