### ISSUE TITLE
Rhasspy Community

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#72]
Hi,
Coming from Snips/Jeedom I'm tryinh Rhasspy solution, which seems pretty awesome.
But it really like a real community. I can only find a single thread on homeassistant community. I don't use home assistant so creating an account on a community that I don't use their solution is a bit strange. And following questions/answers on a single thread with more than 1000 answers isn't easy.

Having a rhasspy dedicated community with categories for hardware, config, sentences, intents, wakeword etc would be a real plus for rhasspy and its users.

**Comment by ghost** [comment]
Plus One

**Comment by mathquis** [comment]
+1 :)

**Comment by synesthesiam** [comment]
I will look into this over the holidays. I'm thinking of just creating a Discourse server; I prefer that to Discord chat (though I've barely used Discord).

Any specific thoughts?

**Comment by KiboOst** [comment]
Hi,
Nice to hear that !

Personnally, I'm not fan of discord. Being a chat (realtime talking) is interesting, but only when others you want to talk to are connected also, and with time all informations is lost. Being easily accessible and sorted on a forum like discourse is, I think, a lot better for rhasspy.

**Comment by thomasfals** [comment]
> Hi,
> Nice to hear that !
> 
> Personnally, I'm not fan of discord. Being a chat (realtime talking) is interesting, but only when others you want to talk to are connected also, and with time all informations is lost. Being easily accessible and sorted on a forum like discourse is, I think, a lot better for rhasspy.
 
I can only agree. I think that Rhasspy is on to something and can grow into something really big with a centralised community.

**Comment by KiboOst** [comment]
Discord could be nice between developers of the project. I work on another big project with thousands of users, discourse is awesome with users but we have a discord channel with developers to discuss ideas, features, bugfix and such dev stuff.

**Comment by synesthesiam** [comment]
I've started a site at https://community.rhasspy.org

Over the next week, I'll be announcing it in various places and moving over some existing posts from the HA forum :)

**Comment by KiboOst** [comment]
Awesome !
Just created a login but no activation email on two different one.
Will try later ;-)

**Comment by koenvervloesem** [comment]
Patience you must have, my young padawan ;-) I see that an email has been sent to you six minutes ago, give it some time to arrive.

**Comment by KiboOst** [comment]
Well, I must admit that my patience as always been extremely buggy ...

**Comment by koenvervloesem** [comment]
Hi @KiboOst I noticed your account was still not activated. Probably a problem with the activation email, did you check your SPAM folder? I have activated your account manually now.

**Comment by KiboOst** [comment]
Ah many thanks !!

I tried yesterday to resend email, on two different emails, checked spam and such of course, but never got it.
Thanks ;-)
