### ISSUE TITLE
Jeedom connection

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#73]
Hi,

I see in rhasspy config some connection for home assistant.
Nothing ready yet, but just to know, could you later add a jeedom section to configure some stuff regarding a rhasspy <-> jeedom connection ?
I can develop a jeedom plugin for rhasspy but it seems dedicated to home assistant actually (both settings and lack of community), so I would know if you would agree on such interaction between rhasspy and jeedom before going further with it. If it's something you can do, I can start drawing a jeedom plugin and what we would need on a rhasspy connector part.
Basically we would need to get list of intents from rhasspy, maybe some jeedom intents filtering (snips did it with intentsNameJeedom to send only jeedom intents to their plugin).
Then rhasspy could just send a json when/with:
- wakeword detected, json with which wakeword from which rhasspy device (living room, kitwhen etc)
- intent recognized, json with intent name, entities, query, slots etc
Maybe sendind such json to a jeedom endpoint inside the plugin.
So we could build a jeedom plugin with such endpoint, which could then send intent data to a callback scenario. Then adding commands in the plugin to send speak to a particular rhasspy device.

What do you think about that, or maybe a better solution. Working with rhasspy sending to a plugin endpoint (some post) would avoid using a mqtt daemon always listening and would be better I guess.

**Comment by synesthesiam** [comment]
I'm not familiar with Jeedom, so I need to look into it before providing a complete answer. Rhasspy does support other modes of interaction besides MQTT. The [HTTP API](https://rhasspy.readthedocs.io/en/latest/usage/#http-api) and the [Websocket events](https://rhasspy.readthedocs.io/en/latest/usage/#websocket-events) are the main ways to do this.

How does Jeedom communicate with external services?

**Comment by KiboOst** [comment]
Hi,
Nice, I would prefer to avoid mqtt, idealy I would use an http api, not need any listener, daemon and such. Have to test it regarding performance anyway.

I only see things on connecting rhasspy to ha, I could do the development of jeedom plugin, and needed to know if you was ok about the possibility of adding stuff to support jeedom. So I will look deeper into this.
The http api seems more the opposite, endpoints on some rhasspy. This can be usefull if I can get the list of intents like this for example. But I would need rhasspy, if set as such, to send a json to a jeedom endpoint for some actions like wakeword detected, intent recognized etc.

**Comment by KiboOst** [comment]
I have a working prototype of a jeedom plugin. 

Two things I miss are:
A api/intents to get the list of intent names from rhasspy: https://github.com/synesthesiam/rhasspy/issues/79

I tested listening websocket but it’s not so easy (can’t get something atm), and using mqtt would require dependencies installation  and a listener always listening. 

A more robust and reliable solution would be to set an url inside rhasspy ui settings, and then have rhasspy sending wakeword when detected and intent recognized to this url with parameters. Or even better just intent recognized with the wakeword in the json  payload. 
This would allow having a nice plugin inside jeedom to set one scenario per intent with slots and such sent to the scenario to treat all sort of complex intent. 

The plugin show an url than can be used by rhasspy to send the json in the url.
So the user would just copy paste this url into rhasspy setting.
Then rhasspy would send json on this url, it is of type:

> http://jeedomIP:80/core/api/jeeApi.php?plugin=jeerhasspy&apikey=xxxxxapikeyxxxxx&type=jeerhasspy&intent=#intent#

You would just have to replace #intent# by the json

Then the plugin will be notified, find the equipement corresponding to this intent, and start the scenario of this equipement with all the tags fron the intent.

**Comment by KiboOst** [comment]
Let me know if you can add this, or have any question. I can even send you (privately) access to my jeedom test config if you need.

![jeerhasspy](https://user-images.githubusercontent.com/26087854/70863594-13e46e80-1f4a-11ea-8113-8b07d25498e6.jpg)

Of course here I manually created intents, waiting for api/intents to automatically create all intents from rhasspy.

**Comment by KiboOst** [comment]
Hi,

I don't think you have to add a special settings for Jeedom, as this is just sending the intent json to an url you could add a new "Send json to URL" setting. This could also be usefull for other solutions/use.

**Comment by KiboOst** [comment]
Ok I did a simple test, but code is a bit hard to understand, even being a python dev. Not easy with so many classes when not mine lol

anyway in intent.py FsticuffsRecognizer.in_loaded I added a request.get to my jeedom plugin url, and it works perfect. Jeedom plugin receive the intent, and start the corresponding scenario with entities etc as tags.

```
            get_url = 'http://111IP111:80/core/api/jeeApi.php?plugin=jeerhasspy&apikey=xxxapikeyxxx&type=jeerhasspy&intent=' + str(intent)
            response = requests.get(get_url)
            self._logger.debug("GETed intent to %s", get_url)
```

Can you please add settings for publishing intent to url when recognized ?

**Comment by synesthesiam** [comment]
OK, I could add this as an intent handling system. Do you need an option to GET or POST, or can it always just POST JSON?

**Comment by KiboOst** [comment]
Actually I only need GET ;-)

I guess we would need some json to url encoded string, such one works for example :

http://111IP111:80/core/api/jeeApi.php?plugin=jeerhasspy&apikey=xxxapikeyxxx&type=jeerhasspy&intent={%22intent%22:{%22name%22:%22lightsSetJeedom%22,%22confidence%22:1.0},%22entities%22:[{%22entity%22:%20%22state%22,%22value%22:%22off%22},{%22entity%22:%22name%22,%22value%22:%22living%20room%20lamp%22}]}

**Comment by mathquis** [comment]
Passing JSON in a GET query string seems inappropriate. A POST request would be better. 

Typically GET is for fetching data and POST is for pushing data... If Rhasspy must send data to a remote HTTP endpoint then I think POST would make more sense. 

@KiboOst Do you think Jeedom or your plugin can handle POST requests instead (I do not know the Jeedom API or plugin system)?

**Comment by KiboOst** [comment]
I can agree on this, I will have to get requests package and do some simple testing to see if the plugin react nice to POST before you spend some time on this. I will let you know

**Comment by KiboOst** [comment]
Ok, POST works perfectly

I have set a test setup with simple python script and requests, here is the script calling the url:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

import json
import requests

post_url = '--get url from rhasspy settings ui'
intent = {"intent": {"name": "lightsSetJeedom", "confidence": 1.0}, "entities": [{"entity": "house_room", "value": "cuisine", "raw_value": "cuisine", "start": 26, "raw_start": 26, "end": 33, "raw_end": 33, "tokens": ["cuisine"], "raw_tokens": ["cuisine"]}], "text": "allume la lumière dans la cuisine", "raw_text": "allume la lumière dans la cuisine", "recognize_seconds": 0.004139713000000711, "tokens": ["allume", "la", "lumière", "dans", "la", "cuisine"], "raw_tokens": ["allume", "la", "lumière", "dans", "la", "cuisine"], "speech_confidence": 0.016240005716861187, "wakeId": "snowboy/hey_brigitte.pmdl", "siteId": "Salon"}

data_json = json.dumps(intent)
response = requests.post(post_url, data={'payload' : data_json})
print(response)
```

Then it works perfect in Jeedom plug, my scenario is started with all necessary data and I can turn light on or whatever

> [2019-12-17 11:51:52][SCENARIO] Start : Lancement provoque. Tags : {"#intent#":"lightsSetJeedom","#confidence#":"1","#wakeword#":"snowboy\/hey_brigitte.pmdl","#query#":"allume la lumi\u00e8re dans la cuisine","#siteId#":"Salon","#house_room#":"cuisine"}

@synesthesiam  
So I only need POST, check script above I used same python module as in core.py
We need in ui, setting, a way to enter an url for *intent handling system: send request to url*

About requests.post, I tried with json= and lot of stuff, but dumping the intent and send it in a simple json payload is the only reliable solution I get working with complex multi level json (like entities array and such).

If you add this, I will have some doc to do for the plugin but all is ready to publish it in beta !

**Comment by koenvervloesem** [comment]
> "allume la lumi\u00e8re dans la cuisine"

You have some wrong character encoding stuff somewhere.

**Comment by KiboOst** [comment]
Once the commit is done I can see where the function is called and debug it if necessary, on rhasspy side or plugin side.

**Comment by KiboOst** [comment]
@synesthesiam Let me know if you have all you need ?

On my side, all is ready, just waiting your commit ;-)

Testing/Developing intents with live connection to Jeedom and a few virtual equipments would be awesome.

**Comment by KiboOst** [comment]
Hi,
I saw intent remote handler and tried it, but you don't use my code and it receive nothing (the function is called in jeedom).
Also I got four calls per intent in same second:


> example : 
> [2019-12-19 20:59:41][DEBUG] : [jeerhasspy] <event> POST: []
> [2019-12-19 20:59:41][DEBUG] : [jeerhasspy] <event> GET: {"plugin":"jeerhasspy","apikey":"xxxxxxxxxxxxxx","type":"jeerhasspy","intent":""}
> [2019-12-19 20:59:41][DEBUG] : [jeerhasspy] <event> POST: []
> [2019-12-19 20:59:41][DEBUG] : [jeerhasspy] <event> GET: {"plugin":"jeerhasspy","apikey":"xxxxxxxxxxxxxx","type":"jeerhasspy"}

If I change for
data_json = json.dumps(intent)
                response = requests.post(self.remote_url, data={'payload' : data_json})

I still get four calls, but the second POST got payload with text and full intent.
Like I said if you use request.post with json= complexe json with array are troncated.

**Comment by mathquis** [comment]
I think it should be:
`response = requests.post(self.remote_url, data=data_json)`

No need for a `payload` envelope (same as websocket event and MQTT message).

**Comment by KiboOst** [comment]
If I test that I just get empty POST

But with payload, seems I got strings of strings ! Trying to debug this :-(

**Comment by mathquis** [comment]
I’ve checked the `intent_handler.py` code for remote handler and everything seems fine.

How do you parse the POST request body? It should be a JSON string.

**Comment by KiboOst** [comment]
POST is just empty with original code.

With my python script it is simple enough like this in php:

> $intentRecognized = json_decode($_POST, true);
> $intentName = $intentRecognized['intent']['name'];

Dunno why nothing works. Was exited after a particularly hard day, guess I would better go to bed...

**Comment by mathquis** [comment]
You cannot parse the $_POST variable in PHP as JSON. This variable gets populated with data from a form data encoded payload. 

To parse the POST payload, you need to use:
`json_decode(file_get_contents('php://input'))`

Hope this helps.

**Comment by KiboOst** [comment]
Oh man, totally forgot this one ! Mixing so much languages in a day isn't good for brain ...
Now works perfect !

Just in case, what should I return to not get error ?

> header('Content-Type: application/json');
> echo json_encode(array('speech' => ''));

return an error in handler, doing this:
### intent = response.json()
speech = intent.get("speech", {})

Sorry being really dumb tonight, this day was horrible

**Comment by mathquis** [comment]
I think you can try:
`header('Content-Type: application/json');`
`echo json_encode(array('speech' => array('text' => '')));`

Please check my syntax as I’m answering from my phone... 😬

**Comment by KiboOst** [comment]
WOW! Many thanks, finally my day ends with a bit of fun !
Many thanks dude !!

**Comment by mathquis** [comment]
Glad I could help. 
Now Rhasspy can talk to Jeedom!
😀

**Comment by KiboOst** [comment]
Exactly !

Now would need /api/intents and multiple /intents files working  :smile:

Will add a few more things in the puglin and try to publish a beta soon !
Thanks again

**Comment by KiboOst** [comment]
Ok, I got a beta version of the Jeedom plugin, all works nice actually.
What I miss is base/satellite configuration that would need work on both rhasspy and the plugin, so dunno if I publish it, but if anyone need to test it all is ready.
Would also wait some rhasspy bugfix like microphone busy, multiple intents file, api.intents would make the plugin more reliable, etc.
But once more I can publish the beta plugin if someone want to test it.
Thanks everyone for your help on this topic 😃

**Comment by synesthesiam** [comment]
OK, I've added a `/api/intents` endpoint. It returns JSON with all of the available intents (and all sentence templates as JSON objects, if you're interested). This should work with multiple .ini files in your `intents` directory too :)
