### ISSUE TITLE
update rhasspy

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#75]
Sorry for the dumb question, but how to update rhasspy to get latest commits ?

I see new commits, like multi sentence ini which is really nice, but doing :

sudo apt-get update && sudo apt-get dist-upgrade

show nothing new. Should I git clone again and redo download-dependencies/create-venv ?

Thanks

**Comment by koenvervloesem** [comment]
How did you install Rhasspy? If with `git clone`, then just go to the rhasspy directory and do a `git pull`. After this, restart Rhasspy.

**Comment by KiboOst** [comment]
Thanks, I've done:

> cd rhasspy
> git pull https://github.com/synesthesiam/rhasspy.git

But now got this error:
```
pi@raspberrypi:~ $ rhasspy/run-venv.sh --profile fr
Traceback (most recent call last):
  File "app.py", line 25, in <module>
    from swagger_ui import quart_api_doc
ModuleNotFoundError: No module named 'swagger_ui'
```

Indeed no swagger_ui in rhasspy\.venv\lib\python3.7\site-packages

**Comment by koenvervloesem** [comment]
That's a new dependency.

This should solve it:

./create-venv.sh

**Comment by KiboOst** [comment]
hmm, didn't goes well

`Collecting rhasspy-nlu==0.1.1
  Using cached https://files.pythonhosted.org/packages/8d/76/d033ee6550287163d19eeffdd0105987df6b5ffb8617df3533c51eac6b9f/rhasspy-nlu-0.1.1.tar.gz
Collecting swagger-ui-py==0.1.7
  Downloading https://files.pythonhosted.org/packages/55/e0/1fe8af4f98e462eb8505ba2fc2d4d678d63ef33b662a9c9fdf8d97d1b4b0/swagger-ui-py-0.1.7.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/pi/rhasspy/.venv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dumps3j0/swagger-ui-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dumps3j0/swagger-ui-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dumps3j0/swagger-ui-py/pip-egg-info
         cwd: /tmp/pip-install-dumps3j0/swagger-ui-py/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dumps3j0/swagger-ui-py/setup.py", line 30, in <module>
        package_data=load_package_data(),
      File "/tmp/pip-install-dumps3j0/swagger-ui-py/setup.py", line 10, in load_package_data
        for file_name in os.listdir(os.path.join(cur_dir, 'swagger_ui', data_dir)):
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-dumps3j0/swagger-ui-py/swagger_ui/static'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

And now :
`Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from quart import (
ModuleNotFoundError: No module named 'quart'`

**Comment by koenvervloesem** [comment]
Ok I see the same now.

**Comment by KiboOst** [comment]
`cd rhasspy
sudo rm -rf .venv
./create-venv.sh`

Still same message ;-)

**Comment by synesthesiam** [comment]
This seems really odd. Are you able to do something like this with an error?

```
cd rhasspy
rm -rf .venv/
python3 -m venv .venv
source .venv/bin/activate
pip3 install wheel setuptools
pip3 install -r requirements.txt
```
I'm testing right now on Python 3.6. Maybe I really need to just move to 3.7.

**Comment by KiboOst** [comment]
> pip3 install wheel setuptools

went fine apart three times:
Cache entry deserialization failed, entry ignored

> pip3 install -r requirements.txt

install fine lot of stuff, often got Cache entry deserialization failed, entry ignored
at the end:

```
...
Failed building wheel for openfs
...
rhasspy-nlu 0.1.1 has requirement attrs==19.1.0, but you'll have attrs 19.3.0 which is incompatible.
rhasspy-nlu 0.1.1 has requirement networkx==2.3, but you'll have networkx 2.4 which is incompatible.

 Running setup.py install for openfst ... error
    Complete output from command /home/pi/rhasspy/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-drnltuxk/openfst/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ff6pekg2/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/rhasspy/.venv/include/site/python3.7/openfst:
    running install
    running build
    running build_ext
    building 'pywrapfst' extension
    creating build
    creating build/temp.linux-armv7l-3.7
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/rhasspy/.venv/include -I/usr/include/python3.7m -c pywrapfst.cc -o build/temp.linux-armv7l-3.7/pywrapfst.o -std=c++11 -Wno-unneeded-internal-declaration -Wno-unused-function
    pywrapfst.cc:594:10: fatal error: fst/util.h: Aucun fichier ou dossier de ce type
     #include <fst/util.h>
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
Command "/home/pi/rhasspy/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-drnltuxk/openfst/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ff6pekg2/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/rhasspy/.venv/include/site/python3.7/openfst" failed with error code 1 in /tmp/pip-install-drnltuxk/openfst/
```

**Comment by KiboOst** [comment]
Hi,

Just redone this:

> cd rhasspy
> git pull https://github.com/synesthesiam/rhasspy.git
> sudo rm -rf .venv
> ./create-venv.sh

Now rhasspy start again and seems to work fine !
