### ISSUE TITLE
raspbian Buster venv Segmentation fault

### ISSUE THREAD

**Issue by sffranke** [synesthesiam/rhasspy-hassio-addon#77]
Hi all,
the docker image crashes after trying to set up a wakeword and refuses tu start up again.
So I tried the virtual environment version. It always crashes when restarting after saving changes. 
./run-venv.sh: line 28:  2303 Segmentation fault      python3 app.py "$@"

Any hints how to run this amazing software under raspbian buster?
TIA
Steffen

**Comment by synesthesiam** [comment]
I'm getting a lot of bug reports lately about the latest Rhasspy on Rpi, so I'm guessing there's something out of whack with Python 3.7 and one of the dependencies. I'll take a look ASAP and push a new version soon with (hopefully) some fixes.

**Comment by sffranke** [comment]
At the moment I just restart it after each save 'n crash. I am very impressed of your work, thanks so much for sharing!

**Comment by KiboOst** [comment]
Hi,

I had exact same behavior/error.

Here is my config:
Config:
- Raspberry Pi4 Raspbian Buster Lite
- ReSpeaker 2Mic with seed drivers
- Virtual env installed (nothing else on the rpi)
Settings:
- Listen for wake word on start-up
- Custom wake word Snowboy
- Use webrtcvad and listen for silence
- Do speech recognition with pocketsphinx on this device
- Do intent recognition with OpenFST on this device
- Use pico-tts on this device : fr-FR
- Use arecord directly (ALSA) / Default Device
- Use aplay directly (ALSA) / Default Device

But curiously I don't have it anymore ! The only change I can remember of is settings a custom snowboy hotword. Not sure if realated of course.

**Comment by frkos** [comment]
Just switched from ALSA to pyAudio and had the same issue...
I've tried to change microphone device in settings and found that when I select `2: USB Camera-B4.09.24.1: Audio (hw:1,0)` the issue disappears (I'm using PS3eye camera as a mic)

So in profile I have:
```
    "microphone": {
        "pyaudio": {
            "device": "3"
        }
    }
```
Please try to do the same, maybe it will help you too
I'm in the middle of testing but the result is promising

**Comment by NullEnt1ty** [comment]
In my case this was fixed by switching from *PyAudio* to *arecord*. I'm using the *ReSpeaker 2 mic array* which seems to act odd with PyAudio.

This is the content of my `asound.conf` file if someone wants to debug:

```
defaults.pcm.rate_converter "samplerate"

pcm.!default {
    type asym
    playback.pcm "playback"
    capture.pcm "capture"
}

pcm.playback {
    type plug
    slave.pcm "dmixed"
}

pcm.capture {
    type plug
    slave.pcm "array"
}

pcm.dmixed {
    type dmix
    slave.pcm "hw:seeed2micvoicec"
    ipc_key 555555 
}

pcm.array {
    type dsnoop
    slave {
        pcm "hw:seeed2micvoicec"
        channels 2
    }
    ipc_key 666666
}
```

**Comment by moritzschaefer** [comment]
I still face this exact same issue (Pi 3B). I pulled the most recent git repository and each time I save+restart from within the webapp, I get the segfault.
