### ISSUE TITLE
api /text-to-speech language

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#78]
Hi,

I don't see in api a way to send a language param for text-to-speech.

Would it be possible ? Ask /api/text-to-speech with a string and a lang parameter so I can ask to say this in fr, en etc ?

**Comment by koenvervloesem** [comment]
Right, that would be interesting indeed. But that requires that Rhasspy has multiple language profiles active at the same time. Currently Rhasspy only loads one profile.

**Comment by synesthesiam** [comment]
For the text to speech system, this was actually quite easy to add. The voice and/or language is passed on the command line or to the API call each time, so it's just a matter of overriding it once.

I've pushed this into `master` :)  The `/api/text-to-speech` endpoint will now take `voice` and `language` parameters. For most TTS systems, they will be the same thing. For MaryTTS and Google TTS, however, you can independently set the voice and language.

**Comment by KiboOst** [comment]
Thanks, will test that !

**Comment by KiboOst** [comment]
Works perfect ;-) thanks again
