### ISSUE TITLE
/api/intents

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#79]
Hi,

Would it be possible to use an API call like /api/intents to get the list of intents set in rhasspy ? Supporting multiple sentences.ini in new intents folder ?

it would just return a list of all intents names defined in rhasspy.

**Comment by KiboOst** [comment]
Got a prototype of a jeedom plugin and really lack this one. 
Next step would be to get wakeword detected and intent recognised.

**Comment by synesthesiam** [comment]
This could be useful as well if the named entities were included with each intent.

For the time being, you could use /api/sentences and match lines like "[IntentName]"

**Comment by KiboOst** [comment]
Will try to parse the answer to get them, thanks.

Anyway with lot of sentences, dunno with it could reach a maximum message lenght ?

Rhasspy having the list of intents, would be a lot safer to get api/intents ;-)

**Comment by KiboOst** [comment]
Hi,
Actually /api/sentences doesn't return intents from profile /intents/ files but only from sentences.ini

Having /api/intents with all intents from all files would really help, thanks

**Comment by synesthesiam** [comment]
Pushed a commit with `/api/intents` endpoint :)

**Comment by KiboOst** [comment]
Awesome, thanks ! Works perfect.

Still can't put more than one file into profile intents folder anyway

**Comment by KiboOst** [comment]
Hi,

I've switched to docker install as it seems more reliable, but seems there is no /api/intents ?
