### ISSUE TITLE
websocket pass wakeword

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#80]
Hi,

Would it be possible to add the wakeword that asked something to the websocket ?

With several custom wakeword we can know which person ask something, and treat it differently regarding who it is. So having it in the json would help sorting such case.

**Comment by mathquis** [comment]
I agree that having which wake word triggered the ASR and intent would allow for user management in the intent handlers. 

This was really missing from Snips’ implementation of the Hermes protocol.

This may lead to some kind of dialog management (session, context, multi step intents, etc...).

**Comment by synesthesiam** [comment]
I've added `wakeId` and `siteId` properties to the recognized intent JSON on `master`. The `wakeId` will be something like "snowboy/jarvis.umdl" and `siteId` will reflect `mqtt.site_id` in your profile.
