### ISSUE TITLE
Language model overrun by complex intents

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#82]
I have an intent with so many sentences that it corrupts the ASR language model.

In intent.json it has `"sentene_count": 50985457958666880` when the others are more in the ballpark of `"sentene_count": 962280`

This is due to order variations of custom and grammar rule based slots like `<datetime>` and `<duration>` and `$artist`.

`wake me up at (<datetime>){date} in ($room){room} with ($artist){artist}`
`wake me up in ($room){room} at (<datetime>){date} with ($artist){artist}`
`wake me up with ($artist){artist} at (<datetime>){date} in ($room){room}`
`wake me up at (<datetime>){date} with ($artist){artist} in ($room){room}`
etc...

I don't know if this is a good idea but maybe slots (anything of the form `(...){name}`) should not be counted for weight/count calculation of intents. All slot values should count as the same weight.

What do you think?

_FYI: I think these is a typo in the property name "sentence_count" ;)_

**Comment by KiboOst** [comment]
How do you define/use datetime and duration slots ?? Would really need them to be able to replace snips (still a long way though ...)

**Comment by mathquis** [comment]
I made them myself based on the [SetTimer voice2json recipe](http://voice2json.org/recipes.html#set-and-run-timers).

I plan on using either [Snips NLU](https://snips-nlu.readthedocs.io/en/latest/) or a library like [duckling](https://duckling.wit.ai/) to parse the extracted values.

For the moment, these corrupt the ASR language model as they increase the number of variations to infinity and beyond.

I hope @synesthesiam can help solve this so we can move to the next stage (providing builtin slots for each language).

**Comment by synesthesiam** [comment]
For now, I can just exclude slots from the sentence count calculation (typo fixed!). I wonder what Snips did in this case.

**Comment by mathquis** [comment]
According to their paper on ASR/NLU on the edge, Snips is using an on the fly Kaldi GrammarFST system. Their entities are provided as separated binary wFST and the intents are provided as another wFST. Everything is stitched up at startup time by their ASR software using something really similar to Kaldi GrammarFST decoder. They build their intent FST using the training sentences provided by the user abstracting the slots as non terminals (so they can change the entity values at runtime without recompiling the complete language model).

Using non terminals seems to mean that the weight of `play music by (ARTIST)` will be the same for any value in the artists entity hence my proposition above. The weight and quantity of values on the artists entity won’t biase the language model.

Compiling the language model FST by replacing slots by a non terminal, compiling the slot values as subFSTs (rule or value based: anything like (...){name}) may solve this (I’m no expert though...)

For the Kaldi ASR the GrammarFST decoder can stitch these on the fly (reducing the memory footprint). For Pocketsphinx the FSTReplace software can be used to inject the subFSTs ahead of time during training. 

To generate the training sentences for Snips I used a custom language close to the JSGF you implemented but to get good variations I had to use entities to abstract large vocabulary alternatives like a track-word entity for « music, the music, some music, a music, etc... ». This reduced the number of training sentences greatly. 

Hope this helps.

**Comment by mathquis** [comment]
Using the latest release (2.4.14), I tweaked the kaldi `decode.sh` parameters and got near perfect ASR results.

I took the ASR config values from my Snips assistant.

Modifying the `beam` size seems to do most of it and does not impact decoding time.

Here are my parameters (I don't know if these values are advised but it seems to work OK for me)

```
# file: /profiles/fr/kaldi/model/online/conf/online.conf
--feature-type=mfcc
--mfcc-config=/profiles/fr/kaldi/model/online/conf/mfcc.conf
--ivector-extraction-config=/profiles/fr/kaldi/model/online/conf/ivector_extractor.conf
--endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
--online=false
--frame-subsampling-factor=3
--max-active=2500
--min-active=200
--beam=24.0
--lattice-beam=8.0
--acoustic-scale=1.0
--chunk-length=0.25
--do-endpointing=true
--endpoint.rule1.max-relative-cost=10000000000.0
--endpoint.rule1.min-trailing-silence=4.0
--endpoint.rule1.min-utterance-length=0.0
--endpoint.rule1.must-contain-nonsilence=false
--endpoint.rule2.max-relative-cost=5.5
--endpoint.rule2.min-trailing-silence=0.7
--endpoint.rule2.min-utterance-length=0.0
--endpoint.rule2.must-contain-nonsilence=true
--endpoint.rule3.max-relative-cost=8.0
--endpoint.rule3.min-trailing-silence=1.0
--endpoint.rule3.min-utterance-length=0.0
--endpoint.rule3.must-contain-nonsilence=true
--endpoint.rule4.max-relative-cost=2.5
--endpoint.rule4.min-trailing-silence=0.5
--endpoint.rule4.min-utterance-length=0.0
--endpoint.rule4.must-contain-nonsilence=true
--endpoint.rule5.max-relative-cost=10000000000.0
--endpoint.rule5.min-trailing-silence=0.0
--endpoint.rule5.min-utterance-length=10.0
--endpoint.rule5.must-contain-nonsilence=true
```

I'm going to do more tests to confirm this and report back.

Kaldi is taking some time to decode a single WAV file (around 1.3-1.5sec on a powerful desktop computer). Probably because it is executed for each transcription (loading the acoustic model, the language model ,etc...).

Maybe Kaldi can be started once and Rhasspy can push chunks of audio to decode faster like:
https://github.com/gooofy/py-kaldi-asr/blob/master/examples/asr_server.py

**Comment by mathquis** [comment]
I seems the `kaldi/model/online/conf/online.conf` file is overwritten during training.
How can we pass options to the Kaldi decoder then?
Can we add them in the `profile.json`?

**Comment by mathquis** [comment]
I’m still getting ASR transcription corruption from an intent with probably too many variations (9 slots!).

For now I’m going to disable it and move on to adding more intents and more slot values.

If I have the time, I’ll make more tests to see if I can pin point what is causing this issue.

**Comment by mathquis** [comment]
I tested the TDNN 250 model from Paul Guyot and it performs awesomely (around 0.5sec)!

Since the language model provided by Rhasspy is trained using a very limited number of words, it seems to compensate the WER pretty well.

Maybe it can be included by default instead of the bigger full model?

**Comment by synesthesiam** [comment]
Maybe I should do this for the other models too. I doubt too many people are going to be using Rhasspy for open transcription.

**Comment by mathquis** [comment]
When using slots with numerous values, the language model becomes biased toward specific succession of words from both the intent AND the slot values (and sometimes multiple slots). 

I have to artificially increase the number of variations of some intents to try to correct the weight of some ngram-2 and ngram-3. I fear that slots like music artist names with many values might become a nightmare to handle.

Instead of merging the slot values with the intents before the creation of the language model, would it be possible to generate a FST language model for intents only (abstracting slots to some kind of marker) and separated FST language models for each slots and merge them only at the end using FSTReplace or equivalent (to replace the markers with the slot FSTs)?

@synesthesiam Do you think it would help to avoid biasing the language model?

_Note: It might also pave the way to builtin slots..._

**Comment by mathquis** [comment]
I've made additional tests and I can confirm that building the language model from a single ARPA file creates mixup/weighting issues.

Ex:
Intent: `allume ($switch){what} du ($room){where}`
Utterance: `allume la lumière du bureau`
ASR: `allume la lumière du niro`

The `du niro` part is from another intent `joue moi du ($artist){who}` with `niro` in $artist slot value and have a higher weight than `du bureau`

This is incorrect as an utterance starting with `allume la lumière` (turn on the light) should not containt an artist's name... but the word `du` seems to mix both $room and $artist slots.

The graph part starting with `allume la lumière...` should not lead to anything else than a $room slot.

This is very problematic and seems to be the root cause for many ASR/NLU issues I'm faced with.

@synesthesiam How do you think this can be fixed?

**Comment by KiboOst** [comment]
Since I played with duration I have same sort of problems. I guess such builtins slot shouldn't generate same weight as other sentences. Or generate les sentences and been parsed later as such slots.

**Comment by synesthesiam** [comment]
This is a fundamental flaw in the use of ngram models. Rhasspy uses 3-gram language models, so at most three words are taken into account for context (including begin/end of sentence). When decoding, all words outside of the context are forgotten (though the path affects the likelihood).

There's no hope for Pocketsphinx (which only supports 3-gram models), but I believe the use of GrammarFSTs in Kaldi will address the problem. In that case, it seems Kaldi would only ever expand slot values along paths where they could be reached. It's seeming clearer that Rhasspy won't be able to reach the same scale as Snips without using this advanced Kaldi feature.

**Comment by mathquis** [comment]
@synesthesiam Do you have plan to support this GrammarFST feature of Kaldi in the near future (Like for version 0.25)?

**Comment by mathquis** [comment]
@synesthesiam I’m experimenting with Kaldi GrammarFST.

I still have a lot of stuff to do (I’ve got some strange issue with the lexicon but I’m pretty sure it comes from my end). 

The results are promising though 😊

**Comment by mathquis** [comment]
Homerun for the GrammarFST language model... 100% correct ASR with Kaldi in french with minimal beams and max-actives :)

Using online decoding will even speed things tenfolds!

**Comment by synesthesiam** [comment]
This is excellent news! Are you doing this through bash scripting? Any example code?

**Comment by mathquis** [comment]
I’m using a home made Node.js script to parse my intents grammar (very simple one with just alternatives), generate all the possible sentences and replace the slots by non terminals « tags ». 
This is pretty quick as most of the variations comes from slot values anyway. This creates the intents corpus. 

Then, I generate a separated corpus for each gazetteer slot (music artists, radio stations, rooms, etc). 

For grammar based slots I used Snips’ FSTs and reformatted then a bit. I got date time, duration, number and percent for free without generating all possible values 👍. Using a JSGF grammar will allow to create and maintain these from scratch. 

I generate the lexicon from these corpus and FSTs. Phonetisaurus for the g2p of unknown words. 

I run prepare_lang.sh (but this might be replaced by code I think). 

From here I create a HCLG.fst for intents and for each slot (using KenLM to create an ARPA lm and arpa2fst to create G.fst, then mkgraph.sh but I could probably use compile-graph binary) that are then composed into a grammar FST using Kaldi binary make-grammar-fst binary. 

I’m thinking that the graph building process could be free of Kaldi bash scripts and only use their binaries.

The decoding part is done using the Kaldi binary online2-wav-nnet3-latgen-grammar. 

I converted around 60 intents from a dozen apps and fed my Snips unit-tests WAV files to the decoder. 

The results are even better than Snips’ (though the decoding use probably more resources) as some words were not transcribed correctly by their ASR. More tests are still required though. 😊

**Comment by mathquis** [comment]
I'm thinking that intents can also be considered non terminals... This could allow to completely bypass the NLU decoding and just require the parsing of the slot values... I will be experimenting more... Interesting times :)

EDIT: I did not find how to nest non terminals...

**Comment by synesthesiam** [comment]
Work for this has moved to https://github.com/rhasspy/rhasspy-asr-kaldi
