### ISSUE TITLE
Can't train - Command failed: ngrammake

### ISSUE THREAD

**Issue by Ulrar** [synesthesiam/rhasspy-hassio-addon#83]
Hi,

I just managed to install rhasspy in a virtual env on a rpi 2 earlier. There's no audio on that pi, but I can use my browser to speak and it kind of doesn't understand me (it really really thinks the work "main" is "make" for some reason for example).

Trying to run the "Train" button instantly fails, with this error :

```
Command failed: 'ngrammake /home/rhasspy/.config/rhasspy/profiles/en/intent.fst.counts /home/rhasspy/.config/rhasspy/profiles/en/intent.fst.model' returned 1
Traceback (most recent call last):
  File "/home/rhasspy/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/rhasspy/rhasspy/.venv/lib/python3.7/site-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "app.py", line 571, in api_train
    raise Exception(f"Training failed: {result.reason}")
Exception: Training failed: <Task: language_model:intent_model>: TaskFailed
Command failed: 'ngrammake /home/rhasspy/.config/rhasspy/profiles/en/intent.fst.counts /home/rhasspy/.config/rhasspy/profiles/en/intent.fst.model' returned 1
```

I tried running the command manually : 
```bash
$ source .venv/bin/activate
$ export LD_LIBRARY_PATH="/home/rhasspy/rhasspy/.venv/lib:${LD_LIBRARY_PATH}"
$ .venv/bin/ngrammake /home/rhasspy/.config/rhasspy/profiles/en/intent.fst.counts /home/rhasspy/.config/rhasspy/profiles/en/intent.fst.model
FATAL: NGramKatz: No discount bin for discounting
```

Maybe I forgot something but I can't find anything about that error on google, just the source file which isn't very helpful.
Thanks

**Comment by synesthesiam** [comment]
Hi @Ulrar could you share your sentences? Maybe there's a bug related to parsing them. Thanks!

**Comment by Ulrar** [comment]
Hey,

Not much, I'm just starting out really :

```
[GetTime]
what time is it
tell me the time

[ChangeLightState]
light_name = (living room light) {name}
light_state = (on | off) {state}

turn <light_state> [the] <light_name>
turn [the] <light_name> <light_state>
turn <light_state> [the] <light_name>

[ChangeLightColor]
light_name = (living room main light) {name}
color = (red | green | blue) {color}

set [the] <light_name> [to] <color>
make [the] <light_name> <color>
```

**Comment by mathquis** [comment]
The error seems to come from these 2 lines:
`turn [the] <light_name> <light_state>`
`turn <light_state> [the] <light_name>`

If only one of these is present, the training succeed.
If both are present, it fails.

I don't know why though.
Maybe a loop between `<light_name>` and `<light_state>`?

**Comment by tobe2bcon** [comment]
Hi,
I'm new here. Coming from snips Iwa looking for an alternative and  installed rhasspy on raspberry pi3 in a virtual environment. Running the "Train" button results in this error message:

> Training failed: <Task: language_model:intent_counts>: TaskFailed Command failed: 'ngramcount /home/pi/.config/rhasspy/profiles/en/intent.fst /home/pi/.config/rhasspy/profiles/en/intent.fst.counts' returned 1 

As mathquis advised I checked the sentences.ini file and deleted the second line. However the error remains. Furthermore I found that "intent.fst" does not exist in any profile. Re-downloading the profile also didn't help. Has anyone got an idea how to resolve?

**Comment by tobe2bcon** [comment]
Hi again,

I found, that obviously ngram was missing. Reloading the profile didn't help. So I have downloaded opengrm-ngram-1.3.4.targ.gz. In which directory does it need to be installed? Any hints to install correctly. Thanks in advance

**Comment by synesthesiam** [comment]
Looking into this issue now (discussion [here](https://community.rhasspy.org/t/hard-time-with-training/96)).

If you build `opengrm` from source, set `--prefix=/path/to/rhasspy/.venv` and when you do `make install` it should create `.venv/bin` and `.venv/lib`.

**Comment by synesthesiam** [comment]
I've pushed a fix for this in the latest Docker image. Using a different smoothing method with `ngrammake`.

**Comment by timaschew** [comment]
I have a similar problem when installing rhasspy on a raspberry via git and virtualenv 
version: https://github.com/synesthesiam/rhasspy/commit/ec55dbfa5bb21528e87ce852f004094ebac70fdf

I've followed the client/server tutorial. Server side training (running via docker) works fine.
I wonder why do I need to train the client and server?

there is the full stack trace:

```
INFO:__main__:Starting training
DEBUG:DialogueManager:asleep -> training_sentences
DEBUG:SnowboyWakeListener:listening -> loaded
[2020-01-03 21:44:52,643] 192.168.178.21:59842 GET /api/unknown-words 1.1 200 2 16323
INFO:quart.serving:192.168.178.21:59842 GET /api/unknown-words 1.1 200 2 16323
WARNING:train:Unsupported acoustic model type: remote
DEBUG:train:Parsing ini file(s): ['/home/pi/rhasspy/profiles/en/sentences.ini']
DEBUG:rhasspynlu.ini_jsgf:Loaded ini file
.  ini_graph
-- intent_fst
.  language_model:intent_counts
ngramcount: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ngramcount)
ngramcount: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /home/pi/rhasspy/.venv/lib/libngram.so.134)
TaskFailed - taskid:language_model:intent_counts
Command failed: 'ngramcount /home/pi/.config/rhasspy/profiles/en/intent.fst /home/pi/.config/rhasspy/profiles/en/intent.fst.counts' returned 1

########################################
language_model:intent_counts <stdout>:

DEBUG:DialogueManager:training_sentences -> ready
INFO:DialogueManager:Automatically listening for wake word
DEBUG:DialogueManager:ready -> asleep
ERROR:__main__:Training failed: <Task: language_model:intent_counts>: TaskFailed
Command failed: 'ngramcount /home/pi/.config/rhasspy/profiles/en/intent.fst /home/pi/.config/rhasspy/profiles/en/intent.fst.counts' returned 1
Traceback (most recent call last):
  File "/home/pi/rhasspy/.venv/lib/python3.6/site-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/pi/rhasspy/.venv/lib/python3.6/site-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "app.py", line 574, in api_train
    raise Exception(f"Training failed: {result.reason}")
Exception: Training failed: <Task: language_model:intent_counts>: TaskFailed
Command failed: 'ngramcount /home/pi/.config/rhasspy/profiles/en/intent.fst /home/pi/.config/rhasspy/profiles/en/intent.fst.counts' returned 1
```

I've check the path and it does exist in my rhasspy venv directory:

```
$ ls -al .venv/bin/ngramcount
-rwxr-xr-x 1 pi pi 1440456 Nov 24 19:51 .venv/bin/ngramcount
```

**Comment by tobe2bcon** [comment]
Hi, sorry for my late response. I've been ill since christmas. So thank
you for your time spent on this issue. In the meantime I have done a
complete re-installation with buster instead of strectch and can
confirm, what others reported as well, that this works fine.
Am Dienstag, den 24.12.2019, 08:03 -0800 schrieb Michael Hansen:
