### ISSUE TITLE
Rhasspy + Logitech Media Server: Conflict?

### ISSUE THREAD

**Issue by vash3d** [synesthesiam/rhasspy-hassio-addon#84]
Setting a new Raspberry 3 to host Rhasspy and LMS bring me to a strange issue:

First attempt
Starting with a clean Raspbian image, I’ve installed Rhasspy as per instruction and it was working flawless.
Then I’ve installed LMS and squeezelight client cause I need to use the raspberry in a multiroom audio system via airplay.
After LMS installation Rhasspy stopped working and the whole system became sluggish and unresponsive.

Second attempt:
Started from scratch I proceeded backwards.
I’ve installed LMS and client, then Rhasspy and as soon as I’ve set which card to use (Rhasspy settings) again the system became unresponsive, LMS and Rhasspy didn’t work anymore and speakers started to buzz.
Stopping Rhasspy docker image seems to solve the issue.

Things to note:
I’ve disabled the onboard audio card and I’m using a Respeaker 2 hat.
The issue seems to start when in Rhasspy settings I try to change from default card (for record and play) to Respeaker.
But having disabled the onboard card default card and Respeaker card are the same.

**Comment by synesthesiam** [comment]
Hmmm...is this because Rhasspy and LMS are each trying to get exclusive access to the Respeaker through ALSA? If so, a solution might be to install PulseAudio.

**Comment by vash3d** [comment]
Thanks for the suggestion.
I've started messing around with pulseaudio but it's a nightmare to setup and I haven't found a guide that could help me.
So I tried a simpler workaround: I've re-enabled the default raspberry audio card, so now I have two card listed with `aplay -l`

```
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
```

I would like to setup Rhasspy to use the onboard card (that I will not use to play audio) and leave the respeaker card to LMS.
However when I select a card in Rhasspy settings page and hit save, Rhasspy restart but then in audio settings I always find "Default device" selected.
And for what concerning audio recording Rhasspy show me all the available card but  if I hit the TEST button it gives me "null discard all settings..."
Manually selecting a card, saving and restarting gives me the same result as Audio Playing: it revert back to "Default card".

Do you think there is something I can try?
thanks

**Comment by vash3d** [comment]
Update:
I've Set PyAudio for recording and manually modified card settings for playing in the profile file.
Seems the way to go. I'll make some testing and if it all works I will close the issue.
Still open to suggestions for a better way to handle this.

**Comment by vash3d** [comment]
Ok, after some trial and error I think I've found a "stable" configuration.
It was the squeezelite player and NOT the server to create the coflict with Rhasspy.
So with inboard card and respeaker card both enabled I've setup 
- Squeezelite to use respeaker card
- Rhasspy playing section to use inboard card (maual setup in the Advanced Panel)

Then for Rhasspy recording section I've somehow ended up with this configuration:
```
"microphone": {
        "arecord": {
            "device": "hw:CARD=seeed2micvoicec,DEV=0"
        },
        "pyaudio": {
            "device": "2"
        }

```
Does it make sense to you?

However I've ordered an usb card cause I want to try to leave respeaker exclusively for Rhasspy (so I can ear the beeping sound of the wake word) and use the usb card for squeezlite.
I think it should work better.

**Comment by synesthesiam** [comment]
So is this related to audio output then, instead of audio input?

**Comment by vash3d** [comment]
Well,I think the lagging issue was related to audio output. From when I've started to use two cards one for Rhasspy and one for Squeezelite player the problem hasn't came anymore.
However Rhasspy is not behaving reliably.
When I test microphone from settings it often gives me only the "null" option as working even if the microphone is actually working fine.
When it recognize the wakeword the beeping sound came out really strange, as it was reproduced at low frequency.
After the wakeword it often doesn't get the vocal command or sometimes it waits the 30 sec. timeout and then execute the command as it doesn't recognize the silence after the command.
And the most annoying thing (but probably this is not related specifically to Rhasspy) it wakes up not only with "false positive" while we are talking, but even when it hears some noise.

This is my current configuration:

```
"microphone": {
        "arecord": {
            "device": "default:CARD=seeed2micvoicec"
        },
        "system": "arecord"
    },
    "sounds": {
        "aplay": {
            "device": "hw:CARD=seeed2micvoicec,DEV=0"
        }
    },
    "wake": {
        "snowboy": {
            "model": "snowboy/morgan.pmdl",
            "sensitivity": "0.5"
        },
        "system": "snowboy"
    }
```

**Comment by frkos** [comment]
> After the wakeword it often doesn't get the vocal command or sometimes it waits the 30 sec. timeout and then execute the command as it doesn't recognize the silence after the command.

It's possible to tune this behavior... You can decrease the timeout and adjust sensitivity
https://rhasspy.readthedocs.io/en/latest/command-listener/#webrtcvad



> it wakes up not only with "false positive" while we are talking, but even when it hears some noise.

I think it's not Rhasspy fault... Try to play with Snowboy `"sensitivity": "0.5"` or even try to switch to Porcupine wake word. Just several clicks


Rhasspy is very flexible, that's why I like it. But it may take some time to tune it for your needs.

**Comment by vash3d** [comment]
> It's possible to tune this behavior... You can decrease the timeout and adjust sensitivity
> https://rhasspy.readthedocs.io/en/latest/command-listener/#webrtcvad

I've tried to add webrtcvad settings in Advanced panel, but when I save and restart Rhasspy it deletes the webrtcvad part.

As for snowboy if I decrease sensitivity to 0.4 it doesn't wake up anymore.
I trying to avoid Porcupine because of the 30 day renewal thing.
And Pocketsphinx never worked for me, maybe because I use a single word without "hey" or "ok" and probably it's to short.

**Comment by koenvervloesem** [comment]
It’s no coincidence that all major voice assistants have a wakeword with three or four syllables: “Hey Google”, “Alexa”, “Hey Siri”, “Cortana”.

There are some [guidelines for choosing a wakeword](https://picovoice.ai/docs/choose-wake-word/). They are:

- avoid short single words;
- avoid long phrases;
- choose words with diverse sounds.

Following these guidelines will improve wakeword recognition.

**Comment by vash3d** [comment]
yep, I know... but one of the reason I'm using Rhasspy is for the custom wake word without hey etc...
Anyway, I'm pretty sure there is even a problem of "white noise" with the respeaker 2 microphone.
I'm playing around with the various level in alsamixer and I'm already having better results, especially concerning the waiting for the silence.

**Comment by frkos** [comment]
> I've tried to add webrtcvad settings in Advanced panel, but when I save and restart Rhasspy it deletes the webrtcvad part.

I found Rhasspy deletes your config parameters when:
Your parameter value mathces default values
or
You have incorrect json format, for example forgot comma after a bracket, etc.

Also you  need to refresh (Ctrl+R) the page in your browser after reboot 

FYI, here is my profile (I'm trying to find the best values for me, so you will probably need to modify them)
```
{
    "command": {
        "webrtcvad": {
            "min_sec": 5,
            "speech_buffers": 10,
            "throwaway_buffers": 15,
            "timeout_sec": 8
        }
    },
    "handle": {
        "system": "hass"
    },
    "home_assistant": {
        "access_token": "XXXXXXXXXXXXXXXX",
        "url": "http://X.X.X.X:8123"
    },
    "microphone": {
        "pyaudio": {
            "device": "2"
        }
    },
    "text_to_speech": {
        "system": "picotts"
    },
    "wake": {
        "system": "snowboy"
    }
}
```
