### ISSUE TITLE
wakeword and site_id in json intent

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#85]
Hi,

I think we would really need a setting into Rhasspy to set the room where the device is. A siteId for example so each rhasspy device has a distinct name.

And join this siteId and a reference of wakeword id that asked.

So, talking about conversation, we can know who ask and where he is.
My goal is to achieve a master/satellite configuration like with snips. Didn't know if it's doable right now, lot of things to test before, but it will allow to send the tts answer to the right device/room.

;-)

**Comment by KiboOst** [comment]
Just saw your commit with message.intent["siteId"] = self.site_id

Thanks for that, but where can we specify this site_id ?

**Comment by synesthesiam** [comment]
This should be in `mqtt.site_id` in your profile for now. You don't have to enable MQTT, but I figured I'd re-use the setting.
