### ISSUE TITLE
error python3 app.py "$@"

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#89]
An error I often have after ui ask for a restart. Here just after changing sentences tab and save:

```
INFO:quart.serving:192.168.0.10:50081 GET /api/unknown-words 1.1 200 2 19205
DEBUG:train:Parsing ini file(s): ['/home/pi/.config/rhasspy/profiles/fr/sentences.ini', '/home/pi/.config/rhasspy/profiles/fr/intents/CloseCoverJeedom.ini', '/home/pi/.config/rhasspy/profiles/fr/intents/lightsSetJeedom.ini']
DEBUG:rhasspynlu.ini_jsgf:Loaded ini file
.  ini_graph
.  intent_fst
.  language_model:intent_counts
.  language_model:intent_model
.  language_model:intent_arpa
.  vocab
.  vocab_dict
DEBUG:vocab_dict:Forcing lower-case
DEBUG:vocab_dict:Loading dictionary from /home/pi/.config/rhasspy/profiles/fr/custom_words.txt
DEBUG:vocab_dict:Loading dictionary from /home/pi/.config/rhasspy/profiles/fr/base_dictionary.txt
DEBUG:vocab_dict:Loaded 74 word(s) from /home/pi/.config/rhasspy/profiles/fr/vocab.txt
DEBUG:DialogueManager:training_sentences -> training_intent
INFO:DialogueManager:Training complete
DEBUG:DialogueManager:Reloading actors
malloc(): unsorted double linked list corrupted
rhasspy/run-venv.sh: line 28:  1190 Aborted                 python3 app.py "$@"
```

My config is:

> Config:
> - Raspberry Pi4 Raspbian Buster Lite
> - ReSpeaker 2Mic with seed drivers
> - Virtual env installed
> Settings:
> - Listen for wake word on start-up
> - Custom wake word Snowboy
> - Use webrtcvad and listen for silence
> - Do speech recognition with pocketsphinx on this device
> - Do intent recognition with OpenFST on this device
> - Use pico-tts on this device : fr-FR
> - Use arecord directly (ALSA) / Default Device
> - Use aplay directly (ALSA) / Default Device
> 
> Started : rhasspy/run-venv.sh --profile fr

**Comment by synesthesiam** [comment]
I'm seeing this too occasionally, and I'm baffled. This has to be one of the Python extensions that's calling out to C or C++ code. I thought for a while it was PyAudio, but it seems you're already using `arecord` instead.

Most of the systems you're using have a C/C++ extension to do their business. Maybe building from source would fix this? I'm still trying to get things to compile on my Pi 3 without it becoming unresponsive. I use Docker and qemu to build the ARM libraries on my server; maybe there's some incompatibility?

**Comment by synesthesiam** [comment]
Hopefully this has been resolved by using Docker.
