### ISSUE TITLE
Allow ApplyFrontend setting for snowboy wake word

### ISSUE THREAD

**Issue by troytc** [synesthesiam/rhasspy-hassio-addon#9]
As documented in the snowboy repo: https://github.com/Kitt-AI/snowboy

Is ApplyFrontend set to true by default, or is it left unset?  This param is required for some of the universal models provided by snowboy.

**Comment by synesthesiam** [comment]
I was unaware of this setting. I'll go ahead and add it to the web interface. Thanks.

**Comment by synesthesiam** [comment]
Fixed in Rhasspy 2.01.
