### ISSUE TITLE
[Feature] Support grammar based slots

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#92]
As a first step towards "builtin" slots (#40), it would be awesome to support slots with values based on JSGF grammar for things like `number`, `temperature`, `date`, etc.

Slots seems compiled as FSTs during training so why not compile slots just like intents allowing rules and all the JSGF grammar awesomeness in the process?

In the future, these slots might be provided directly by Rhasspy for each language and maintained by the community for everyone to use out of the box (it would really ease the setup process for non technical folks).

_NOTE: This may require that we find a viable solution to the biased language model issue (#58)._ 

What do you think?

**Comment by koenvervloesem** [comment]
> maintained by the community for everyone to use

Are you sure the community is up to the task? Creating and maintaining language rules is a tough nut to crack. Companies like Snips employ language experts for this, and adding grammar rules for a new language (granted, this is much more than slots) takes them months of work.

**Comment by mathquis** [comment]
We do not need a complete language grammar, just specific pieces for variable part in intents. As I said above, providing these may be a future stage. In the meantime, it would be awesome to be able to extract these rules/logic to slots instead of putting it in the intents as rules.

The most complex grammar based slot I have come across is the `datetime` one. I already put together rules to handle basic usage in french (`date`, `time`, `datetime`, `relative_date`, `relative_datetime`, etc.).

It may be a limited as I'm sure that I haven't though of every possible variations but it works.

Sharing these with the community and improving them together would be a lot easier (detect edge cases, add variations, etc.)

**Comment by koenvervloesem** [comment]
> In the meantime, it would be awesome to be able to extract these rules/logic to slots instead of putting it in the intents as rules.

This would indeed be very welcome to simplify the intent rules.

**Comment by synesthesiam** [comment]
Discussion continued here: https://community.rhasspy.org/t/support-grammar-based-slots/51
