### ISSUE TITLE
 '/home/pi/rhasspy/profiles/de/sentences.ini' does not start with '/home/pi/.config/rhasspy/profiles/de'

### ISSUE THREAD

**Issue by patrickjane** [synesthesiam/rhasspy-hassio-addon#93]
I just did a fresh installation (venv method) on a clean and new raspbian stretch installation (on a pi 3), and I get the following error in the web GUI:

```
 '/home/pi/rhasspy/profiles/de/sentences.ini' does not start with '/home/pi/.config/rhasspy/profiles/de'
```

Also, when going to sentences, it looks pretty empty:

https://imgur.com/a/M0whJmE

So I can see that I have both directories:
```
pi@henrietta:~/rhasspy $ ll ~/.config/rhasspy/profiles/de/
total 15M
drwxr-xr-x 6 pi pi  4.0K Dec 17 20:37 .
drwxr-xr-x 4 pi pi  4.0K Dec 17 21:05 ..
drwxrwxr-x 2 pi pi  4.0K Dec 17  2017 acoustic_model
-rw-rw-r-- 1 pi pi 1021K Dec 17  2017 base_dictionary.txt
-rw-r--r-- 1 pi pi    47 Dec 17 20:37 .doit.db.bak
-rw-r--r-- 1 pi pi   721 Dec 17 20:37 .doit.db.dat
-rw-r--r-- 1 pi pi    47 Dec 17 20:37 .doit.db.dir
drwxr-xr-x 2 pi pi  4.0K Dec 17 20:35 download
drwxr-xr-x 2 pi pi  4.0K Dec 17 20:37 fsts
-rw-r--r-- 1 pi pi   14M May 14  2019 g2p.fst
drwxr-xr-x 2 pi pi  4.0K Dec 17 20:37 grammars
-rw-r--r-- 1 pi pi  2.5K Dec 17 20:37 intent.fst
-rw-r--r-- 1 pi pi  5.9K Dec 17 20:37 intent.json
```

and 

```
pi@henrietta:~/rhasspy $ ll profiles/de
total 416K
drwxr-xr-x  3 pi pi 4.0K Dec 17 17:11 .
drwxr-xr-x 16 pi pi 4.0K Dec 17 17:11 ..
-rwxr-xr-x  1 pi pi   90 Dec 17 17:11 custom_words.txt
-rwxr-xr-x  1 pi pi  631 Dec 17 17:11 dictionary.txt
-rwxr-xr-x  1 pi pi  321 Dec 17 17:11 espeak_phonemes.txt
-rwxr-xr-x  1 pi pi 298K Dec 17 17:11 frequent_words.html
-rw-r--r--  1 pi pi  45K Dec 17 17:11 frequent_words.phones
-rwxr-xr-x  1 pi pi  22K Dec 17 17:11 frequent_words.txt
drwxr-xr-x  2 pi pi 4.0K Dec 17 17:11 kaldi
-rwxr-xr-x  1 pi pi 3.0K Dec 17 17:11 language_model.txt
-rwxr-xr-x  1 pi pi 1.1K Dec 17 17:11 phoneme_examples.txt
-rwxr-xr-x  1 pi pi 3.4K Dec 17 17:11 profile.json
-rwxr-xr-x  1 pi pi  326 Dec 17 17:11 sentences.ini
-rw-r--r--  1 pi pi 1.4K Dec 17 17:11 stop_words.txt
```

What should I do?

Weird thing is, I was having a clean installation on another pi like 2 days ago, following the exact same steps, and I ended up with a working sentences.ini. Now it no longer the case as it seems.

**Comment by richardmward** [comment]
I too experienced this (with an `en` profile), but with the latest docker image as a fresh installation yesterday. Adding a sentences.ini with some content resolved it, however, previously a sentences.ini file would be present with some default config.

**Comment by patrickjane** [comment]
Okay well the sentences.ini with the predefined defaults *is* present, its in `/home/pi/rhasspy/profiles/de/sentences.ini`. So should this be put into `~/.config/rhasspy/profiles/de/` now instead? What about the other stuff in the `/home/pi/rhasspy/profiles/de` folder?

**Comment by synesthesiam** [comment]
Sorry, fix for this has been pushed. Should be live soon!

**Comment by synesthesiam** [comment]
Fix is now in the latest Docker image. Please re-open if issue continues!
