### ISSUE TITLE
Slots get multiplied every time you save the slots

### ISSUE THREAD

**Issue by drhirn** [synesthesiam/rhasspy-hassio-addon#96]
I have the following slot-definition:
`{
    "activities": [
        "netflix",
        "amazon",
        "fernsehen",
        "youtube"
    ],
    "color": [
        "red",
        "green",
        "blue"
    ],
    "direction": [
        "left",
        "right"
    ],
    "rooms": [
        "küche",
        "schlafzimmer",
        "vorraum",
        "wohnzimmer",
        "bad",
        "klo",
        "garten",
        "keller"
    ]
}`

Everytime I save the slots, all entries are added to the slot-files. Added! So after some time, a slot-file looks like this:

> küche
> schlafzimmer
> vorraum
> wohnzimmer
> bad
> klo
> küche
> schlafzimmer
> vorraum
> wohnzimmer
> bad
> klo
> garten
> küche
> schlafzimmer
> vorraum
> wohnzimmer
> bad
> klo
> garten
> keller

Not sure if this is intended.

**Comment by synesthesiam** [comment]
Yikes. I know what's wrong. Will fix ASAP.

**Comment by synesthesiam** [comment]
Should be fixed now in the latest Docker image. Please re-open if it continues.
