### ISSUE TITLE
Training bug : ZeroDivisionError

### ISSUE THREAD

**Issue by KiboOst** [synesthesiam/rhasspy-hassio-addon#97]
Just updated rhasspy, re download profile, restarted, and when doing train :

`Training failed: <Task: ini_graph>: TaskError PythonAction Error Traceback (most recent call last): File "/home/pi/rhasspy/.venv/lib/python3.7/site-packages/doit/action.py", line 424, in execute returned_value = self.py_callable(*self.args, **kwargs) File "/home/pi/rhasspy/rhasspy/train/__init__.py", line 206, in do_intents_to_graph graph = intents_to_graph(intents, replacements) File "/home/pi/rhasspy/.venv/lib/python3.7/site-packages/rhasspynlu/jsgf_graph.py", line 213, in intents_to_graph num_sentences_lcm = lcm(*intent_counts.values()) File "/home/pi/rhasspy/.venv/lib/python3.7/site-packages/rhasspynlu/jsgf_graph.py", line 491, in lcm nums_lcm = (nums_lcm * n) // math.gcd(nums_lcm, n) ZeroDivisionError: integer division or modulo by zero `

If I remove all in config/intents, it works
If I put only one file into config/intents, it works
If I puth them both, crash

Here the intent ini files:

> [CloseCoverJeedom]
> ferme [le | les] ($window_devices){window_devices} [du | de la] ($house_room){house_room}

> [lightsSetJeedom]
> allume la lumière [de | dans] [la | le] ($house_room){house_room}
> mets de la lumière dans [la | le] ($house_room){house_room}

**Comment by KiboOst** [comment]
If I remove in each file the first [intentname] line, training works.
But intent recognition always find GetTime (default from sentences.ini), with right slots, but never got the right intent even saying exact same sentence as defined.

**Comment by KiboOst** [comment]
With only CloseCoverJeedom.ini file and [CloseCoverJeedom] in the file, training AND recognition works !

**Comment by KiboOst** [comment]
Ok, created a third file:
/intents/TurnOnJeedom.ini

> 
> [TurnOnJeedom]
> mets [de] [la | le] ($device_name){device_name} dans le ($house_room){house_room}
> lance [de] [la | le] ($device_name){device_name} dans le ($house_room){house_room}
> allume [la | le] ($device_name){device_name} dans le ($house_room){house_room}

Again:

File alone, training and intent recognition works.
As soon as I add a second intent file training crash with division by zero
Same behavior for each file, works alone.

**Comment by synesthesiam** [comment]
This is likely due to how I changed the sentence count calculation for slots. I'll add your examples as a test case in rhasspy-nlu and get this fixed.

Thanks for your testing and patience!

**Comment by KiboOst** [comment]
No problem, still testing, far from production, just want rhasspy to be the best :-)

Let me know if I can help in any way

**Comment by KiboOst** [comment]
Just for info, just updated rhasspy (got api/intents working) but still exact case. Can't put more than one file into .config/rhasspy/profiles/fr/intents

But, if I put four files into intents folder, doing /api/intents return all the intents from the four files. So the problem isn't the algo checking files into the folder.

**Comment by KiboOst** [comment]
Ok, more on the subject:

I take four of my intent files and combine them into one file that I put into ui sentence tab

> [GetTime]
> quelle heure est-il
> il est quelle heure
> 
> [lightsTurnOnJeedom]
> allume [la | les] lumière [de | du | dans] [la | le] ($house_room){house_room}
> allume ($lights_type){lights_type} [des | les] les lumières du ($house_room){house_room}
> allume [le | la] ($house_room){house_room}
> mets de la lumière dans [la | le] ($house_room){house_room}
> 
> [lightsTurnOffJeedom]
> éteins [la | les] lumière [de | dans] [la | le] ($house_room){house_room}
> éteins ($lights_type){lights_type} [des | les] lumières du ($house_room){house_room}
> éteins [le | la] ($house_room){house_room}
> coupe la lumière dans [la | le] ($house_room){house_room}
> 
> [OpenCoverJeedom]
> ouvre [le | les] ($window_devices){window_devices}
> ouvre [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> ouvre ($window_state){window_state} [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> monte [le | les] ($window_devices){window_devices}
> monte [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> monte ($window_state){window_state} [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> lève [le | les] ($window_devices){window_devices}
> lève [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> lève ($window_state){window_state} [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> 
> [CloseCoverJeedom]
> ferme [le | les] ($window_devices){window_devices}
> ferme [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> ferme ($window_state){window_state} [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> baisse [le | les] ($window_devices){window_devices}
> baisse [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> baisse ($window_state){window_state} [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> descends [le | les] ($window_devices){window_devices}
> descends [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}
> descends ($window_state){window_state} [le | les] ($window_devices){window_devices} [dans] [du | de la ] [le] ($house_room){house_room}


It crash with exact same message (ZeroDivisionError)
So it's not a problem of being seperated files !
More a problem regarding number of intents. Seems in totality being sentences.ini and intent files, I can't get more than two intents...

Now in this sentences I keep all sentence, but keep only the two first [intentNames]
=> training works !

So at least it's not my sentences syntax. Which I ever knew, as alone, each intent file works.

**Comment by KiboOst** [comment]
Still exact same problem with a docker container install
https://community.rhasspy.org/t/keep-rhasspy-running/73/10

If you need my slots intents folder zipped let me know, I really can't test further rhasspy as I can't have more than two intents.

Dunno if it comes from pi4/buster, wanted a pi3B+ for rhasspy testing but couldn't find one in stock and I guess it should work anyway on pi4.

**Comment by KiboOst** [comment]
docker/python 3.6 error

> 
> Exception: Training failed: <Task: ini_graph>: TaskError
> PythonAction Error
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/doit/action.py", line 424, in execute
>     returned_value = self.py_callable(*self.args, **kwargs)
>   File "/usr/share/rhasspy/rhasspy/train/__init__.py", line 207, in do_intents_to_graph
>     graph = intents_to_graph(intents, replacements)
>   File "/usr/local/lib/python3.6/dist-packages/rhasspynlu/jsgf_graph.py", line 213, in intents_to_graph
>     num_sentences_lcm = lcm(*intent_counts.values())
>   File "/usr/local/lib/python3.6/dist-packages/rhasspynlu/jsgf_graph.py", line 491, in lcm
>     nums_lcm = (nums_lcm * n) // math.gcd(nums_lcm, n)
> ZeroDivisionError: integer division or modulo by zero

**Comment by KiboOst** [comment]
@synesthesiam 
Tried intent recognition fuzzywuzzy, openFST with or without Fuzzy text matching, same error each time.

**Comment by synesthesiam** [comment]
OK, can I get all of your sentences and slots in a zip file? I can fix the zero division error, but I want to understand what's causing it in the first place.

**Comment by KiboOst** [comment]
Here it is, it is part of my .config/.../fr profil with slots and intents
Each works separately, put two of them and division by zero happend

[fr.zip](https://github.com/synesthesiam/rhasspy/files/3991835/fr.zip)

**Comment by KiboOst** [comment]
Did you had time to test my zip ?
Would really know if it comes from some of my sentence/syntax or slots or whatever.

**Comment by synesthesiam** [comment]
Just tested it with the French profile and had no troubles. My changes to the `rhasspy-nlu` library must have fixed the problems. If you're already up to date on `master`, make sure you do a `pip3 install --upgrade rhasspy-nlu` to make sure you get version `1.0.3` installed.

Please let me know if that works :)

**Comment by KiboOst** [comment]
I switched to docker but will try with venv.

**Comment by KiboOst** [comment]
Ok, pulled git, updated nlu, deleted and recreated venv

Running venv, I can now have several intents working !
I have some files that cause crash anyway, but without any help to know wha the problem is. Maybe a syntax validation tool could help, which check files one by ones, then sentences one by one.

Running back to docker, seems it doesn't get the new nul, division by zero still there.

Thanks ;-)

**Comment by synesthesiam** [comment]
Updated the Docker image, so hopefully you can use that now. Syntax checking is definitely something I miss from using a proper parser. I switched to a custom one after getting terrible performance with lots of alternatives.
