### ISSUE TITLE
tests.sh fails - `GLIBC_2.27' not found (required by ngramcount)

### ISSUE THREAD

**Issue by reklawykSekuL** [synesthesiam/rhasspy-hassio-addon#99]
I 've made a manual Installation on a "respeaker coreV2".

Installation finished without error, the web GUI runs - but when i run  tests.sh  there are error messages like this:
 `DEBUG:rhasspynlu.ini_jsgf:Loaded ini file
.  ini_graph
.  intent_fst
.  language_model:intent_counts
ngramcount: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ngramcount)
ngramcount: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /home/respeaker/rhasspy/.venv/lib/libngram.so.134)`
` 
sollte die GLIBC_2.27   in die virtuelle Umgebung installiert werden/sein ?
wenn ja   wie kann man das nachträglich installieren ?

**Comment by synesthesiam** [comment]
Which version of Raspbian are you on?

**Comment by reklawykSekuL** [comment]
it's an [respeaker core v2](http://wiki.seeedstudio.com/ReSpeaker_Core_v2.0/) it runs on a Debian 9
so i can **NOT** use the images for Raspbian.
The glibc 2.27 seems to be a dev-branch - is not found in the official [debian-glibc-pool](http://ftp.debian.org/debian/pool/main/g/glibc) 
maybe i should try to build the ngram... from source?

**Comment by synesthesiam** [comment]
I've been working on a build-from-source.sh script in the repo. I'm having a hard time getting opengrm to build on the Pi without adding a lot more swap space.

The script should at least help you get started.

**Comment by synesthesiam** [comment]
See documentation here on building from source: https://rhasspy.readthedocs.io/en/latest/installation/#build-from-source
